#lang typed/racket

(provide Dye Blockdef symbol->blockdef fixnum->blockdef
         (struct-out blockdef))

; WARNING - This file really gives the macro expander a workout!
; So consider making changes in blockdef.rkt instead whenever possible.

(define-type Dye (U 'white 'black 'purple 'pink 'red 'green 'yellow 'blue))

(struct blockdef ([id : Fixnum]
                  [symbol : Symbol]
                  [liquid? : Boolean]
                  [star? : Boolean]
                  [dyes : (Listof (Pairof Dye Fixnum))])
  #:transparent #:type-name Blockdef)

(define-syntax-rule (parseblock id sym lower-name liquid? star? dyes)
  (blockdef id (quote sym) liquid? star? (quote dyes)))

(define-syntax-rule (define-stuff [symbol->blockdef fixnum->blockdef]
                      (id symbol lower-name liquid? star? dyes)
                      ...)
  (begin
    (define (symbol->blockdef x)
      (case x
        [(symbol) (parseblock id symbol lower-name liquid? star? dyes)]
        ...
        [else #f]))
    (define (fixnum->blockdef x)
      (case x
        [(id) (parseblock id symbol lower-name liquid? star? dyes)]
        ...
        [else #f]))))

; From generate-case-expr.rkt
(define-stuff [symbol->blockdef fixnum->blockdef]
  (1 Bedrock "bedrock" #f #f ())
  (2 Earth "earth" #f #f ())
  (3 Grassy-Earth "grassy earth" #f #f ())
  (4 Limegrassy-Earth "limegrassy earth" #f #f ())
  (5 Tilled-Soil "tilled soil" #f #f ())
  (6 Clay "clay" #f #f ())
  (7 Mossy-Earth "mossy earth" #f #f ())
  (8 Chalk "chalk" #f #f ())
  (9 Chunky-Chalk "chunky chalk" #f #f ())
  (10 Obsidian "obsidian" #f #f ())
  (11 Sand "sand" #f #f ())
  (12 Sandstone "sandstone" #f #f ())
  (13 Sandy-Sandstone "sandy sandstone" #f #f ())
  (14 Bloodstone "bloodstone" #f #f ())
  (15 Ash "ash" #f #f ())
  (16 Witchgrassy-Earth "witchgrassy earth*" #f #t ())
  (17 Poisonous-Peat "poisonous peat" #f #f ())
  (18 Snow-Cover "snow cover" #f #f ())
  (19 Snow "snow" #f #f ())
  (20 Ice "ice" #f #f ())
  (21 Clodstone "clodstone" #f #f ())
  (22 Crumbly-Clodstone "crumbly clodstone" #f #f ())
  (23 Basalt "basalt" #f #f ())
  (24 Translucent-Block "translucent block" #f #f ())
  (25 Lava "lava" #f #f ())
  (26 Vault-Wall "vault wall" #f #f ())
  (27 Viny-Vault-Wall "viny vault wall" #f #f ())
  (28 Cracked-Vault-Wall "cracked vault wall" #f #f ())
  (29 Mud-Brick-Wall "mud-brick wall" #f #f ())
  (30 Timbered-Foundation "timbered foundation" #f #f ((white . 277) (black . 278) (purple . 279) (pink . 280) (red . 281) (green . 282) (yellow . 283) (blue . 284)))
  (31 Timbered-Wall-Midsection "timbered wall midsection" #f #f ((white . 285) (black . 286) (purple . 287) (pink . 288) (red . 289) (green . 290) (yellow . 291) (blue . 292)))
  (32 Timbered-Capital "timbered capital" #f #f ((white . 293) (black . 294) (purple . 295) (pink . 296) (red . 297) (green . 298) (yellow . 299) (blue . 300)))
  (33 Hardwood-Pedestal "hardwood pedestal" #f #f ((white . 359) (black . 360) (purple . 361) (pink . 362) (red . 363) (green . 364) (yellow . 365) (blue . 366)))
  (34 Hardwood-Column-Midsection "hardwood column midsection" #f #f ((white . 351) (black . 352) (purple . 353) (pink . 354) (red . 355) (green . 356) (yellow . 357) (blue . 358)))
  (35 Hardwood-Capital "hardwood capital" #f #f ((white . 367) (black . 368) (purple . 369) (pink . 370) (red . 371) (green . 372) (yellow . 373) (blue . 374)))
  (36 Stone-Foundation "stone foundation" #f #f ())
  (37 Stone-Wall-Midsection "stone wall midsection" #f #f ())
  (39 Castle-Foundation "castle foundation" #f #f ())
  (40 Castle-Wall-Midsection "castle wall midsection" #f #f ())
  (41 Castle-Crenellation "castle crenellation" #f #f ())
  (42 Castle-Battlement "castle battlement" #f #f ())
  (43 Wooden-Wall "wooden wall" #f #f ((white . 301) (black . 302) (purple . 303) (pink . 304) (red . 305) (green . 306) (yellow . 307) (blue . 308)))
  (44 Plumberry-Lumber "plumberry lumber" #f #f ())
  (45 Flagstone "flagstone" #f #f ())
  (46 Straw-Floor "straw floor" #f #f ())
  (47 Wooden-Floor "wooden floor" #f #f ((white . 317) (black . 318) (purple . 319) (pink . 320) (red . 321) (green . 322) (yellow . 323) (blue . 324)))
  (48 Hardwood-Tile "hardwood tile" #f #f ((white . 463) (black . 464) (purple . 465) (pink . 466) (red . 467) (green . 468) (yellow . 469) (blue . 470)))
  (49 Purple-Flagstone "purple flagstone" #f #f ())
  (50 Blue-Flagstone "blue flagstone" #f #f ())
  (51 Carpet-Midsection "carpet midsection" #f #f ((white . 375) (black . 376) (purple . 377) (pink . 378) (red . 379) (green . 380) (yellow . 381) (blue . 382)))
  (52 Fancy-Carpet "fancy carpet" #f #f ((white . 269) (black . 270) (purple . 271) (pink . 272) (green . 273) (yellow . 274) (blue . 275) (red . 276)))
  (53 Castle-Tile "castle tile" #f #f ((white . 654) (black . 655) (purple . 656) (pink . 657) (red . 658) (green . 659) (yellow . 660) (blue . 661)))
  (54 Carved-Castle-Tile "carved castle tile" #f #f ((white . 662) (black . 663) (purple . 664) (pink . 665) (red . 666) (green . 667) (yellow . 668) (blue . 669)))
  (57 Bronze-Temple-Tile "bronze temple tile" #f #f ())
  (58 Blue-Temple-Tile "blue temple tile" #f #f ())
  (61 Golemite "golemite*" #f #t ())
  (62 Coal-Vein "coal vein" #f #f ())
  (63 Copper-Vein "copper vein" #f #f ())
  (64 Iron-Vein "iron vein" #f #f ())
  (65 Silver-Vein "silver vein" #f #f ())
  (66 Gold-Vein "gold vein" #f #f ())
  (67 Zenithium-Vein "zenithium vein" #f #f ())
  (68 Ruby-Vein "ruby vein" #f #f ())
  (69 Mythril-Vein "mythril vein" #f #f ())
  (70 Orichalcum-Vein "orichalcum vein" #f #f ())
  (73 Golemite "golemite" #f #f ())
  (74 Palm-Lumber "palm lumber" #f #f ())
  (75 Cedar-Lumber "cedar lumber" #f #f ())
  (76 Time-Honoured-Turf "time-honoured turf" #f #f ())
  (77 8-Bit-Brick "8-bit brick" #f #f ())
  (78 Olde-Worlde-Wall "olde worlde wall" #f #f ())
  (79 Eyewall "eyewall" #f #f ())
  (80 Dummy-Block "dummy block" #f #f ())
  (81 Witchgrassy-Earth "witchgrassy earth" #f #f ())
  (82 Lemongrassy-Earth "lemongrassy earth" #f #f ())
  (83 Unused-Ore "unused ore" #f #f ())
  (85 Strange-Sand "strange sand" #f #f ())
  (86 Unused-Lava-Block "unused lava block" #f #f ())
  (87 Unused-Ice-Block "unused ice block" #f #f ())
  (88 Bonestone "bonestone" #f #f ())
  (89 Hargon-Block "hargon block" #f #f ())
  (90 Slimy-Block "slimy block" #f #f ())
  (91 Retro-Roof "retro roof" #f #f ())
  (92 Black-Block "black block" #f #f ())
  (93 Grey-Block "grey block" #f #f ())
  (94 White-Block "white block" #f #f ())
  (95 Burgundy-Block "burgundy block" #f #f ())
  (96 Red-Block "red block" #f #f ())
  (97 Purple-Block "purple block" #f #f ())
  (98 Pink-Block "pink block" #f #f ())
  (99 Green-Block "green block" #f #f ())
  (100 Lime-Green-Block "lime-green block" #f #f ())
  (101 Orange-Block "orange block" #f #f ())
  (102 Yellow-Block "yellow block" #f #f ())
  (103 Navy-Block "navy block" #f #f ())
  (104 Blue-Block "blue block" #f #f ())
  (105 Beige-Block "beige block" #f #f ())
  (106 Cyan-Block "cyan block" #f #f ())
  (107 Silver-Block "silver block" #f #f ())
  (108 Gold-Block "gold block" #f #f ())
  (109 Fortress-Foundation "fortress foundation" #f #f ())
  (110 Fortress-Wall-Midsection "fortress wall midsection" #f #f ())
  (111 Fortress-Battlement "fortress battlement" #f #f ())
  (115 Clodstone "clodstone*" #f #t ())
  (118 Crumbly-Clodstone "crumbly clodstone" #f #f ())
  (119 Tilled-Soil "tilled soil" #f #f ())
  (120 Clear-water-full-block "clear water full block" #t #f ())
  (121 Clear-water-surface-block "clear water surface block" #t #f ())
  (122 Clear-water-surface-block "clear water surface block" #t #f ())
  (123 Clear-water-surface-block "clear water surface block" #t #f ())
  (124 Witchgrassy-Block "witchgrassy block*" #f #t ())
  (125 Lemongrassy-Block "lemongrassy block*" #f #t ())
  (126 Grassy-Block "grassy block*" #f #t ())
  (127 Limegrassy-Block "limegrassy block*" #f #t ())
  (128 Clear-water-full-block "clear water full block" #t #f ())
  (130 Light-Dolomite "light dolomite" #f #f ())
  (131 Dark-Dolomite "dark dolomite" #f #f ())
  (132 Stony-Sand "stony sand" #f #f ())
  (134 Masonry-Wall "masonry wall" #f #f ())
  (138 Mossy-Bark "mossy bark" #f #f ())
  (139 Bark "bark" #f #f ())
  (141 Stony-Soil "stony soil" #f #f ())
  (142 Clear-water-surface-block "clear water surface block" #t #f ())
  (143 Clear-water-surface-block "clear water surface block" #t #f ())
  (144 Clear-water-surface-block "clear water surface block" #t #f ())
  (145 Clear-water-shallow-block "clear water shallow block" #t #f ())
  (146 Seaside-Sand "seaside sand" #f #f ())
  (147 Arid-Earth "arid earth" #f #f ())
  (149 Chert "chert" #f #f ())
  (153 Chunky-Chert "chunky chert" #f #f ())
  (155 Leaves "leaves" #f #f ())
  (156 Spoiled-Soil "spoiled soil" #f #f ())
  (158 Moss "moss" #f #f ())
  (161 Humus "humus" #f #f ())
  (162 Tilled-Humus "tilled humus" #f #f ())
  (163 Obsidian "obsidian*" #f #t ())
  (164 Blue-Temple-Tile "blue temple tile*" #f #t ())
  (165 Chert "chert*" #f #t ())
  (166 Citadel-Battlement "citadel battlement*" #f #t ())
  (167 Golden-Citadel-Capital "golden citadel capital*" #f #t ())
  (168 Alcoved-Citadel-Wall "alcoved citadel wall*" #f #t ())
  (169 Golden-Citadel-Foundation "golden citadel foundation*" #f #t ())
  (170 Sanguine-Cinders "sanguine cinders*" #f #t ())
  (171 Scales "scales*" #f #t ())
  (172 Tilled-Soil "tilled soil" #f #f ())
  (173 Tilled-Humus "tilled humus" #f #f ())
  (174 Chert "chert" #f #f ())
  (175 Bubbling-Seaside-Sand "bubbling seaside sand" #f #f ())
  (176 Patterned-Citadel-Wall "patterned citadel wall*" #f #t ())
  (177 Citadel-Capital "citadel capital*" #f #t ())
  (178 Citadel-Foundation "citadel foundation*" #f #t ())
  (179 Castle-Wall-Midsection "castle wall midsection*" #f #t ())
  (180 Citadel-Floor "citadel floor*" #f #t ())
  (182 Poison-shallow-block "poison shallow block" #t #f ())
  (183 Poison-surface-block "poison surface block" #t #f ())
  (184 Poison-surface-block "poison surface block" #t #f ())
  (185 Poison-surface-block "poison surface block" #t #f ())
  (186 Poison-surface-block "poison surface block" #t #f ())
  (187 Poison-surface-block "poison surface block" #t #f ())
  (188 Poison-surface-block "poison surface block" #t #f ())
  (189 Poison-full-block "poison full block" #t #f ())
  (190 Poison-full-block "poison full block" #t #f ())
  (191 Bottomless-Swamp-shallow-block "bottomless swamp shallow block" #t #f ())
  (192 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (193 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (194 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (195 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (196 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (197 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (198 Bottomless-Swamp-full-block "bottomless swamp full block" #t #f ())
  (199 Bottomless-Swamp-full-block "bottomless swamp full block" #t #f ())
  (200 Muddy-Water-shallow-block "muddy water shallow block" #t #f ())
  (201 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (202 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (203 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (204 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (205 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (206 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (207 Muddy-Water-full-block "muddy water full block" #t #f ())
  (208 Muddy-Water-full-block "muddy water full block" #t #f ())
  (209 Umber "umber" #f #f ())
  (210 Umber-Sandstone-Block "umber sandstone block*" #f #t ())
  (223 Hot-Water-shallow-block "hot water shallow block" #t #f ())
  (224 Hot-Water-surface-block "hot water surface block" #t #f ())
  (225 Hot-Water-surface-block "hot water surface block" #t #f ())
  (226 Hot-Water-surface-block "hot water surface block" #t #f ())
  (227 Hot-Water-surface-block "hot water surface block" #t #f ())
  (228 Hot-Water-surface-block "hot water surface block" #t #f ())
  (229 Hot-Water-surface-block "hot water surface block" #t #f ())
  (230 Hot-Water-full-block "hot water full block" #t #f ())
  (231 Hot-Water-full-block "hot water full block" #t #f ())
  (232 Mossy-Spoiled-Soil "mossy spoiled soil" #f #f ())
  (234 Swampy-Soil "swampy soil" #f #f ())
  (235 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (236 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (239 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (241 Lumpy-Umber "lumpy umber" #f #f ())
  (243 Softwood "softwood" #f #f ())
  (244 Floorboard "floorboard" #f #f ((white . 570) (black . 571) (purple . 572) (pink . 573) (red . 574) (green . 575) (yellow . 576) (blue . 577)))
  (247 Yellow-frame-block "yellow frame block*" #f #t ())
  (256 Moss "moss" #f #f ())
  (259 Lava-shallow-block "lava shallow block" #t #f ())
  (260 Lava-surface-block "lava surface block" #t #f ())
  (261 Lava-surface-block "lava surface block" #t #f ())
  (262 Lava-surface-block "lava surface block" #t #f ())
  (263 Lava-surface-block "lava surface block" #t #f ())
  (263 Chalk "chalk" #f #f ())
  (264 Lava-surface-block "lava surface block" #t #f ())
  (265 Lava-surface-block "lava surface block" #t #f ())
  (266 Lava-surface-block "lava surface block" #t #f ())
  (267 Lava-surface-block "lava surface block" #t #f ())
  (268 Patterned-Vault-Wall "patterned vault wall" #f #f ())
  (331 Shifting-Sand "shifting sand" #f #f ())
  (333 Sea-water-shallow-block "sea water shallow block" #t #f ())
  (334 Sea-water-surface-block "sea water surface block" #t #f ())
  (335 Sea-water-surface-block "sea water surface block" #t #f ())
  (336 Sea-water-surface-block "sea water surface block" #t #f ())
  (337 Sea-water-surface-block "sea water surface block" #t #f ())
  (338 Sea-water-surface-block "sea water surface block" #t #f ())
  (339 Sea-water-surface-block "sea water surface block" #t #f ())
  (340 Sea-water-full-block "sea water full block" #t #f ())
  (341 Sea-water-full-block "sea water full block" #t #f ())
  (343 Clear-water-shallow-block "clear water shallow block" #t #f ())
  (344 Hot-water-shallow-block "hot water shallow block" #t #f ())
  (345 Poison-shallow-block "poison shallow block" #t #f ())
  (346 Lava-shallow-block "lava shallow block" #t #f ())
  (347 Bottomless-Swamp-shallow-block "bottomless swamp shallow block" #t #f ())
  (348 Muddy-Water-shallow-block "muddy water shallow block" #t #f ())
  (349 Sea-water-shallow-block "sea water shallow block" #t #f ())
  (383 Clear-water-surface-block "clear water surface block" #t #f ())
  (384 Hot-water-surface-block "hot water surface block" #t #f ())
  (385 Poison-surface-block "poison surface block" #t #f ())
  (386 Lava-surface-block "lava surface block" #t #f ())
  (387 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (388 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (389 Sea-water-surface-block "sea water surface block" #t #f ())
  (390 Plasma-shallow-block "plasma shallow block" #t #f ())
  (391 Plasma-surface-block "plasma surface block" #t #f ())
  (392 Plasma-surface-block "plasma surface block" #t #f ())
  (393 Plasma-surface-block "plasma surface block" #t #f ())
  (394 Plasma-surface-block "plasma surface block" #t #f ())
  (395 Plasma-surface-block "plasma surface block" #t #f ())
  (396 Plasma-surface-block "plasma surface block" #t #f ())
  (397 Plasma-full-block "plasma full block" #t #f ())
  (398 Plasma-full-block "plasma full block" #t #f ())
  (399 Plasma-shallow-block "plasma shallow block" #t #f ())
  (400 Plasma-surface-block "plasma surface block" #t #f ())
  (401 Vault-Tile "vault tile" #f #f ())
  (402 Gold-Brick "gold brick" #f #f ())
  (403 Spaceship-Wall "spaceship wall" #f #f ((white . 421) (black . 422) (purple . 423) (pink . 424) (red . 425) (green . 426) (yellow . 427) (blue . 428)))
  (404 Shiny-Spaceship-Wall "shiny spaceship wall" #f #f ((white . 429) (black . 430) (purple . 431) (pink . 432) (red . 433) (green . 434) (yellow . 435) (blue . 436)))
  (405 Citadel-Battlement "citadel battlement" #f #f ())
  (407 Golden-Citadel-Capital "golden citadel capital" #f #f ())
  (408 Alcoved-Citadel-Wall "alcoved citadel wall" #f #f ())
  (409 Golden-Citadel-Foundation "golden citadel foundation" #f #f ())
  (410 Patterned-Citadel-Wall "patterned citadel wall" #f #f ())
  (411 Golden-Tile "golden tile" #f #f ())
  (412 Hargon-Block "hargon block*" #f #t ())
  (413 Black-Void "black void" #f #f ())
  (414 Earth "earth*" #f #t ())
  (415 Mossy-Earth "mossy earth*" #f #t ())
  (416 Snow "snow*" #f #t ())
  (417 Clodstone "clodstone*" #f #t ())
  (418 Witchgrassy-Earth "witchgrassy earth*" #f #t ())
  (419 Battlefield-Earth "battlefield earth" #f #f ())
  (420 Sea-water-shallow-block "sea water shallow block" #t #f ())
  (437 Woodless-Timbered-Wall "woodless timbered wall" #f #f ())
  (438 Banded-Timbered-Wall "banded timbered wall" #f #f ((white . 447) (black . 448) (purple . 449) (pink . 450) (red . 451) (green . 452) (yellow . 453) (blue . 454)))
  (472 Red-Brick-Wall "red-brick wall" #f #f ())
  (473 Diamond-Vein "diamond vein" #f #f ())
  (474 Chert-Red "chert (red)*" #f #t ())
  (475 Citadel-Floor-Red "citadel floor (red)*" #f #t ())
  (476 Magnetite-Vein "magnetite vein" #f #f ())
  (477 Siltstone "siltstone" #f #f ())
  (481 Slimy-Block "slimy block" #f #f ())
  (484 Red-Brick-Floor "red-brick floor" #f #f ())
  (485 Crazing-Paving "crazing paving" #f #f ())
  (486 Copper-Wall "copper wall" #f #f ())
  (487 Marble "marble" #f #f ())
  (488 Silver-Birch-Lumber "silver birch lumber" #f #f ())
  (489 Spoiled-Soil "spoiled soil*" #f #t ())
  (491 Dark-Bark "dark bark" #f #f ())
  (492 Teal-Leaves "teal leaves" #f #f ())
  (497 Bloodstained-Soil "bloodstained soil" #f #f ())
  (498 Bloodstained-Soil-full "bloodstained soil full" #f #f ())
  (499 Padded-Floor "padded floor" #f #f ((white . 578) (black . 579) (purple . 580) (pink . 581) (red . 582) (green . 583) (yellow . 584) (blue . 585)))
  (500 Leafy-Spoiled-Soil "leafy spoiled soil" #f #f ())
  (501 Leafy-Spoiled-Soil-full "leafy spoiled soil full" #f #f ())
  (519 Cracked-Floorboard "cracked floorboard" #f #f ())
  (520 Blackened-Bark "blackened bark" #f #f ())
  (521 Bloodstained-Soil-full "bloodstained soil full" #f #f ())
  (522 Malachite "malachite" #f #f ())
  (523 Patterned-Vault-Wall "patterned vault wall*" #f #t ())
  (524 Patterned-Vault-Wall "patterned vault wall*" #f #t ())
  (525 Adobe-Capital "adobe capital" #f #f ())
  (526 Adobe-Wall-Midsection "adobe wall (midsection)" #f #f ())
  (527 Adobe-Pedestal "adobe pedestal" #f #f ())
  (528 Alcoved-Adobe-Wall "alcoved adobe wall" #f #f ())
  (529 Copper-Floor "copper floor" #f #f ())
  (530 Sooty-Softwood "sooty softwood" #f #f ())
  (532 Heartwood "heartwood" #f #f ())
  (533 Plumberry-Lumber "plumberry lumber*" #f #t ())
  (534 White-Dye-Vein "white dye vein" #f #f ())
  (535 Black-Dye-Vein "black dye vein" #f #f ())
  (536 Purple-Dye-Vein "purple dye vein" #f #f ())
  (537 Pink-Dye-Vein "pink dye vein" #f #f ())
  (538 Red-Dye-Vein "red dye vein" #f #f ())
  (539 Green-Dye-Vein "green dye vein" #f #f ())
  (540 Yellow-Dye-Vein "yellow dye vein" #f #f ())
  (541 Blue-Dye-Vein "blue dye vein" #f #f ())
  (543 Blue-Temple-Tile-Half-Dummy "blue temple tile half dummy" #f #f ())
  (544 Carpet "carpet" #f #f ((white . 309) (black . 310) (purple . 311) (pink . 312) (red . 313) (green . 314) (yellow . 315) (blue . 316)))
  (545 Golden-Castle-Capital "golden castle capital" #f #f ())
  (546 Alcoved-Castle-Wall "alcoved castle wall" #f #f ())
  (547 Golden-Castle-Foundation "golden castle foundation" #f #f ())
  (548 Cracked-Castle-Tile "cracked castle tile" #f #f ())
  (549 Battlefield-Earth "battlefield earth" #f #f ())
  (550 Citadel-Capital "citadel capital" #f #f ())
  (551 Citadel-Foundation "citadel foundation" #f #f ())
  (552 Citadel-Wall-Midsection "citadel wall midsection" #f #f ())
  (553 Citadel-Floor "citadel floor" #f #f ())
  (560 Ghost-Block "ghost block*" #f #t ())
  (561 Plaster "plaster" #f #f ((white . 562) (black . 563) (purple . 564) (pink . 565) (red . 566) (green . 567) (yellow . 568) (blue . 569)))
  (586 Leafy-Stony-Soil "leafy stony soil" #f #f ())
  (587 Leafy-Stony-Soil-Full "leafy stony soil full" #f #f ())
  (588 Iron-Block "iron block" #f #f ((white . 638) (black . 639) (purple . 640) (pink . 641) (red . 642) (green . 643) (yellow . 644) (blue . 645)))
  (589 Concrete-Block "concrete block" #f #f ())
  (590 Sun-Sigil-Block "sun sigil block" #f #f ())
  (591 Star-Sigil-Block "star sigil block" #f #f ())
  (592 Moon-Sigil-Block "moon sigil block" #f #f ())
  (593 Water-Sigil-Block "water sigil block" #f #f ())
  (594 Soul-Sigil-Block "soul sigil block" #f #f ())
  (595 Sandstone-Brick "sandstone brick" #f #f ((white . 646) (black . 647) (purple . 648) (pink . 649) (red . 650) (green . 651) (yellow . 652) (blue . 653)))
  (596 Withered-Leaves "withered leaves" #f #f ())
  (598 Arid-Earth "arid earth*" #f #t ())
  (599 Umber "umber*" #f #t ())
  (600 Mossy-Spoiled-Soil "mossy spoiled soil*" #f #t ())
  (601 Swampy-Soil "swampy soil*" #f #t ())
  (602 Lumpy-Umber "lumpy umber*" #f #t ())
  (603 Bloodstained-Soil "bloodstained soil*" #f #t ())
  (604 Leafy-Spoiled-Soil "leafy spoiled soil" #f #f ())
  (606 Sanguine-Sandstone "sanguine sandstone" #f #f ())
  (607 Sanguine-Cinders "sanguine cinders" #f #f ())
  (608 Sanguine-Sand "sanguine sand" #f #f ())
  (609 Sanguine-Sandy-Sandstone "sanguine sandy sandstone" #f #f ())
  (610 Scales "scales" #f #f ())
  (611 Red-Block "red block*" #f #t ())
  (612 Silver-Brick "silver brick" #f #f ())
  (613 Sooty-Silver-Brick "sooty silver brick" #f #f ())
  (614 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (615 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (616 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (617 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (618 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (619 Obsidian "obsidian*" #f #t ())
  (620 Sand "sand*" #f #t ())
  (621 Lava "lava*" #f #t ())
  (622 Umber-Sandstone-Block "umber sandstone block*" #f #t ())
  (624 Silver-Tile "silver tile" #f #f ())
  (625 Obsidian "obsidian" #f #f ())
  (626 Light-Dolomite "light dolomite" #f #f ())
  (627 Clodstone "clodstone" #f #f ())
  (630 Masonry-Wall "masonry wall" #f #f ())
  (631 Patterned-Vault-Wall "patterned vault wall" #f #f ())
  (632 Patterned-Vault-Wall "patterned vault wall" #f #f ())
  (633 Vault-Tile "vault tile" #f #f ())
  (634 Vault-Wall "vault wall" #f #f ())
  (635 Viny-Vault-Wall "viny vault wall" #f #f ())
  (636 Cracked-Vault-Wall "cracked vault wall" #f #f ())
  (637 Black-Void "black void" #f #f ())
  (670 Cyan-Block "cyan block*" #f #t ())
  (671 Green-Block "green block*" #f #t ())
  (672 Purple-Block "purple block*" #f #t ())
  (673 Translucent-Block "translucent block" #f #f ())
  (674 Yellow-Block "yellow block*" #f #t ())
  (675 Orange-Block "orange block*" #f #t ())
  (676 Blue-Block "blue block*" #f #t ())
  (677 Cyan-Block "cyan block*" #f #t ())
  (678 Bronze-Temple-Tile "bronze temple tile" #f #f ())
  (679 Blue-Temple-Tile "blue temple tile" #f #f ())
  (680 Seeded-Limegrassy-Earth "seeded limegrassy earth" #f #f ())
  (681 Seeded-Mossy-Spoiled-Soil "seeded mossy spoiled soil" #f #f ())
  (682 Seeded-Sand "seeded sand" #f #f ())
  (683 Seeded-Earth "seeded earth" #f #f ())
  (684 Seeded-Snow "seeded snow" #f #f ())
  (685 Seeded-Grassy-Earth "seeded grassy earth" #f #f ())
  (686 Gravel-Block "gravel block" #f #f ())
  (687 Scaled-Wall-Block "scaled wall block" #f #f ((white . 694) (black . 695) (purple . 696) (pink . 697) (red . 698) (green . 699) (yellow . 700) (blue . 701)))
  (688 Slatted-Wall-Block "slatted wall block" #f #f ())
  (689 Woven-Straw-Block "woven straw block" #f #f ())
  (690 Woven-Straw-Block "woven straw block" #f #f ())
  (691 Woven-Straw-Block "woven straw block" #f #f ())
  (692 Woven-Straw-Block "woven straw block" #f #f ())
  (693 Woven-Straw-Block "woven straw block" #f #f ())
  (702 Polka-Dot-Block "polka-dot block" #f #f ((white . 703) (black . 704) (purple . 705) (pink . 706) (red . 707) (green . 708) (yellow . 709) (blue . 710)))
  (711 Faux-Floral-Floor-Block "faux floral floor block" #f #f ())
  (712 Palm-Patterned-Block "palm-patterned block" #f #f ((white . 732) (black . 733) (purple . 734) (pink . 735) (red . 736) (green . 737) (yellow . 738) (blue . 739)))
  (713 Fruity-Fiend-Block "fruity fiend block" #f #f ())
  (714 Chequered-Block "chequered block" #f #f ((white . 740) (black . 741) (purple . 742) (pink . 743) (red . 744) (green . 745) (yellow . 746) (blue . 747)))
  (715 Sunset-Styled-Block "sunset-styled block" #f #f ((white . 834) (black . 835) (purple . 836) (pink . 837) (red . 838) (green . 839) (yellow . 840) (blue . 841)))
  (716 Seaweed-Styled-Block "seaweed-styled block" #f #f ((white . 842) (black . 843) (purple . 844) (pink . 845) (red . 846) (green . 847) (yellow . 848) (blue . 849)))
  (717 Stylish-Stripy-Block "stylish stripy block" #f #f ((white . 748) (black . 749) (purple . 750) (pink . 751) (red . 752) (green . 753) (yellow . 754) (blue . 755)))
  (718 Seaside-Scene-Block "seaside scene block" #f #f ())
  (719 Abstract-Floral-Floor-Block "abstract floral floor block" #f #f ())
  (720 Herringbone-Floorboard-Block "herringbone floorboard block" #f #f ((white . 756) (black . 757) (purple . 758) (pink . 759) (red . 760) (green . 761) (yellow . 762) (blue . 763)))
  (721 Night-Sky-Wall-Block "night sky wall block" #f #f ((white . 764) (black . 765) (purple . 766) (pink . 767) (red . 768) (green . 769) (yellow . 770) (blue . 771)))
  (722 Granite-Floor-Block "granite floor block" #f #f ())
  (723 Stucco-Wall-Block "stucco wall block" #f #f ((white . 724) (black . 725) (purple . 726) (pink . 727) (red . 728) (green . 729) (yellow . 730) (blue . 731)))
  (772 Modern-Masonry-Block "modern masonry block" #f #f ((white . 773) (black . 774) (purple . 775) (pink . 776) (red . 777) (green . 778) (yellow . 779) (blue . 780)))
  (781 Chintzy-Block "chintzy block" #f #f ((white . 782) (black . 783) (purple . 784) (pink . 785) (red . 786) (green . 787) (yellow . 788) (blue . 789)))
  (790 Gingham-Carpet "gingham carpet" #f #f ((white . 791) (black . 792) (purple . 793) (pink . 794) (red . 795) (green . 796) (yellow . 797) (blue . 798)))
  (799 Stripy-Wall "stripy wall" #f #f ((white . 800) (black . 801) (purple . 802) (pink . 803) (red . 804) (green . 805) (yellow . 806) (blue . 807)))
  (808 Mottled-Wall "mottled wall" #f #f ((white . 809) (black . 810) (purple . 811) (pink . 812) (red . 813) (green . 814) (yellow . 815) (blue . 816)))
  (817 Slimy-Wall "slimy wall" #f #f ())
  (818 Diamond-Design-Block "diamond design block" #f #f ())
  (819 Old-Skool-Wall-Block "old-skool wall block" #f #f ())
  (820 Art-Deco-Block "art deco block" #f #f ())
  (821 Jungle-Wall "jungle wall" #f #f ())
  (822 Vintage-Wall "vintage wall" #f #f ((white . 850) (black . 851) (purple . 852) (pink . 853) (red . 854) (green . 855) (yellow . 856) (blue . 857)))
  (823 Damask-Design-Block "damask design block" #f #f ((white . 824) (black . 825) (purple . 826) (pink . 827) (red . 828) (green . 829) (yellow . 830) (blue . 831)))
  (832 Refined-Design-Block "refined design block" #f #f ())
  (833 Classy-Cross-Block "classy cross block" #f #f ())
  (1012 Black-Void "black void" #f #f ())
  (1158 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1159 Clear-Water-Shallow-Block "clear water shallow block" #t #f ())
  (1160 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1161 Clear-Water-Small-Block "clear water small block" #t #f ())
  (1162 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1163 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1164 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1165 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1166 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1167 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1168 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1169 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1170 Hot-Water-Shallow-Block "hot water shallow block" #t #f ())
  (1171 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1172 Hot-Water-Small-Block "hot water small block" #t #f ())
  (1173 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1174 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1175 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1176 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1177 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1178 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1179 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1180 Poison-Full-Block "poison full block" #t #f ())
  (1181 Poison-Shallow-Block "poison shallow block" #t #f ())
  (1182 Poison-Surface-Block "poison surface block" #t #f ())
  (1183 Poison-Small-Block "poison small block" #t #f ())
  (1184 Poison-Surface-Block "poison surface block" #t #f ())
  (1185 Poison-Surface-Block "poison surface block" #t #f ())
  (1186 Poison-Surface-Block "poison surface block" #t #f ())
  (1187 Poison-Surface-Block "poison surface block" #t #f ())
  (1188 Poison-Surface-Block "poison surface block" #t #f ())
  (1189 Poison-Surface-Block "poison surface block" #t #f ())
  (1190 Poison-Full-Block "poison full block" #t #f ())
  (1191 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1192 Liquid-Lava-Shallow-Block "liquid lava shallow block" #t #f ())
  (1193 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1194 Liquid-Lava-Small-Block "liquid lava small block" #t #f ())
  (1195 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1196 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1197 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1198 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1199 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1200 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1201 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1202 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1203 Bottomless-Swamp-Shallow-Block "bottomless swamp shallow block" #t #f ())
  (1204 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1205 Bottomless-Swamp-Small-Block "bottomless swamp small block" #t #f ())
  (1206 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1207 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1208 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1209 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1210 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1211 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1212 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1213 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1214 Filthy-Water-Shallow-Block "filthy water shallow block" #t #f ())
  (1215 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1216 Filthy-Water-Small-Block "filthy water small block" #t #f ())
  (1217 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1218 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1219 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1220 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1221 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1222 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1223 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1224 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1225 Sea-Water-Shallow-Block "sea water shallow block" #t #f ())
  (1226 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1227 Sea-Water-Small-Block "sea water small block" #t #f ())
  (1228 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1229 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1230 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1231 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1232 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1233 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1234 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1235 Plasma-Full-Block "plasma full block" #t #f ())
  (1236 Plasma-Shallow-Block "plasma shallow block" #t #f ())
  (1237 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1238 Plasma-Small-Block "plasma small block" #t #f ())
  (1239 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1240 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1241 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1242 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1243 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1244 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1245 Plasma-Full-Block "plasma full block" #t #f ())
  (1247 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1248 Clear-Water-Shallow-Block "clear water shallow block" #t #f ())
  (1249 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1250 Clear-Water-Small-Block "clear water small block" #t #f ())
  (1251 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1252 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1253 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1254 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1255 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1256 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1257 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1258 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1259 Hot-Water-Shallow-Block "hot water shallow block" #t #f ())
  (1260 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1261 Hot-Water-Small-Block "hot water small block" #t #f ())
  (1262 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1263 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1264 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1265 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1266 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1267 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1268 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1269 Poison-Full-Block "poison full block" #t #f ())
  (1270 Poison-Shallow-Block "poison shallow block" #t #f ())
  (1271 Poison-Surface-Block "poison surface block" #t #f ())
  (1272 Poison-Small-Block "poison small block" #t #f ())
  (1273 Poison-Surface-Block "poison surface block" #t #f ())
  (1274 Poison-Surface-Block "poison surface block" #t #f ())
  (1275 Poison-Surface-Block "poison surface block" #t #f ())
  (1276 Poison-Surface-Block "poison surface block" #t #f ())
  (1277 Poison-Surface-Block "poison surface block" #t #f ())
  (1278 Poison-Surface-Block "poison surface block" #t #f ())
  (1279 Poison-Full-Block "poison full block" #t #f ())
  (1280 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1281 Liquid-Lava-Shallow-Block "liquid lava shallow block" #t #f ())
  (1282 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1283 Liquid-Lava-Small-Block "liquid lava small block" #t #f ())
  (1284 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1285 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1286 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1287 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1288 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1289 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1290 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1291 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1292 Bottomless-Swamp-Shallow-Block "bottomless swamp shallow block" #t #f ())
  (1293 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1294 Bottomless-Swamp-Small-Block "bottomless swamp small block" #t #f ())
  (1295 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1296 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1297 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1298 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1299 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1300 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1301 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1302 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1303 Filthy-Water-Shallow-Block "filthy water shallow block" #t #f ())
  (1304 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1305 Filthy-Water-Small-Block "filthy water small block" #t #f ())
  (1306 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1307 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1308 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1309 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1310 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1311 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1312 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1313 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1314 Sea-Water-Shallow-Block "sea water shallow block" #t #f ())
  (1315 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1316 Sea-Water-Small-Block "sea water small block" #t #f ())
  (1317 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1318 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1319 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1320 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1321 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1322 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1323 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1324 Plasma-Full-Block "plasma full block" #t #f ())
  (1325 Plasma-Shallow-Block "plasma shallow block" #t #f ())
  (1326 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1327 Plasma-Small-Block "plasma small block" #t #f ())
  (1328 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1329 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1330 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1331 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1332 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1333 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1334 Plasma-Full-Block "plasma full block" #t #f ())
  (1336 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1337 Clear-Water-Shallow-Block "clear water shallow block" #t #f ())
  (1338 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1339 Clear-Water-Small-Block "clear water small block" #t #f ())
  (1340 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1341 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1342 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1343 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1344 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1345 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1346 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1347 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1348 Hot-Water-Shallow-Block "hot water shallow block" #t #f ())
  (1349 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1350 Hot-Water-Small-Block "hot water small block" #t #f ())
  (1351 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1352 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1353 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1354 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1355 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1356 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1357 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1358 Poison-Full-Block "poison full block" #t #f ())
  (1359 Poison-Shallow-Block "poison shallow block" #t #f ())
  (1360 Poison-Surface-Block "poison surface block" #t #f ())
  (1361 Poison-Small-Block "poison small block" #t #f ())
  (1362 Poison-Surface-Block "poison surface block" #t #f ())
  (1363 Poison-Surface-Block "poison surface block" #t #f ())
  (1364 Poison-Surface-Block "poison surface block" #t #f ())
  (1365 Poison-Surface-Block "poison surface block" #t #f ())
  (1366 Poison-Surface-Block "poison surface block" #t #f ())
  (1367 Poison-Surface-Block "poison surface block" #t #f ())
  (1368 Poison-Full-Block "poison full block" #t #f ())
  (1369 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1370 Liquid-Lava-Shallow-Block "liquid lava shallow block" #t #f ())
  (1371 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1372 Liquid-Lava-Small-Block "liquid lava small block" #t #f ())
  (1373 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1374 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1375 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1376 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1377 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1378 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1379 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1380 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1381 Bottomless-Swamp-Shallow-Block "bottomless swamp shallow block" #t #f ())
  (1382 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1383 Bottomless-Swamp-Small-Block "bottomless swamp small block" #t #f ())
  (1384 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1385 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1386 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1387 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1388 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1389 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1390 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1391 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1392 Filthy-Water-Shallow-Block "filthy water shallow block" #t #f ())
  (1393 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1394 Filthy-Water-Small-Block "filthy water small block" #t #f ())
  (1395 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1396 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1397 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1398 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1399 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1400 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1401 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1402 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1403 Sea-Water-Shallow-Block "sea water shallow block" #t #f ())
  (1404 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1405 Sea-Water-Small-Block "sea water small block" #t #f ())
  (1406 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1407 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1408 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1409 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1410 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1411 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1412 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1413 Plasma-Full-Block "plasma full block" #t #f ())
  (1414 Plasma-Shallow-Block "plasma shallow block" #t #f ())
  (1415 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1416 Plasma-Small-Block "plasma small block" #t #f ())
  (1417 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1418 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1419 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1420 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1421 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1422 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1423 Plasma-Full-Block "plasma full block" #t #f ())
  (1425 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1426 Clear-Water-Shallow-Block "clear water shallow block" #t #f ())
  (1427 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1428 Clear-Water-Small-Block "clear water small block" #t #f ())
  (1429 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1430 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1431 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1432 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1433 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1434 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1435 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1436 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1437 Hot-Water-Shallow-Block "hot water shallow block" #t #f ())
  (1438 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1439 Hot-Water-Small-Block "hot water small block" #t #f ())
  (1440 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1441 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1442 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1443 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1444 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1445 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1446 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1447 Poison-Full-Block "poison full block" #t #f ())
  (1448 Poison-Shallow-Block "poison shallow block" #t #f ())
  (1449 Poison-Surface-Block "poison surface block" #t #f ())
  (1450 Poison-Small-Block "poison small block" #t #f ())
  (1451 Poison-Surface-Block "poison surface block" #t #f ())
  (1452 Poison-Surface-Block "poison surface block" #t #f ())
  (1453 Poison-Surface-Block "poison surface block" #t #f ())
  (1454 Poison-Surface-Block "poison surface block" #t #f ())
  (1455 Poison-Surface-Block "poison surface block" #t #f ())
  (1456 Poison-Surface-Block "poison surface block" #t #f ())
  (1457 Poison-Full-Block "poison full block" #t #f ())
  (1458 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1459 Liquid-Lava-Shallow-Block "liquid lava shallow block" #t #f ())
  (1460 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1461 Liquid-Lava-Small-Block "liquid lava small block" #t #f ())
  (1462 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1463 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1464 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1465 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1466 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1467 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1468 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1469 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1470 Bottomless-Swamp-Shallow-Block "bottomless swamp shallow block" #t #f ())
  (1471 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1472 Bottomless-Swamp-Small-Block "bottomless swamp small block" #t #f ())
  (1473 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1474 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1475 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1476 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1477 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1478 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1479 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1480 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1481 Filthy-Water-Shallow-Block "filthy water shallow block" #t #f ())
  (1482 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1483 Filthy-Water-Small-Block "filthy water small block" #t #f ())
  (1484 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1485 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1486 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1487 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1488 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1489 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1490 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1491 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1492 Sea-Water-Shallow-Block "sea water shallow block" #t #f ())
  (1493 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1494 Sea-Water-Small-Block "sea water small block" #t #f ())
  (1495 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1496 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1497 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1498 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1499 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1500 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1501 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1502 Plasma-Full-Block "plasma full block" #t #f ())
  (1503 Plasma-Shallow-Block "plasma shallow block" #t #f ())
  (1504 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1505 Plasma-Small-Block "plasma small block" #t #f ())
  (1506 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1507 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1508 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1509 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1510 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1511 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1512 Plasma-Full-Block "plasma full block" #t #f ())
  (1514 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1515 Clear-Water-Shallow-Block "clear water shallow block" #t #f ())
  (1516 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1517 Clear-Water-Small-Block "clear water small block" #t #f ())
  (1518 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1519 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1520 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1521 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1522 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1523 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1524 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1525 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1526 Hot-Water-Shallow-Block "hot water shallow block" #t #f ())
  (1527 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1528 Hot-Water-Small-Block "hot water small block" #t #f ())
  (1529 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1530 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1531 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1532 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1533 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1534 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1535 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1536 Poison-Full-Block "poison full block" #t #f ())
  (1537 Poison-Shallow-Block "poison shallow block" #t #f ())
  (1538 Poison-Surface-Block "poison surface block" #t #f ())
  (1539 Poison-Small-Block "poison small block" #t #f ())
  (1540 Poison-Surface-Block "poison surface block" #t #f ())
  (1541 Poison-Surface-Block "poison surface block" #t #f ())
  (1542 Poison-Surface-Block "poison surface block" #t #f ())
  (1543 Poison-Surface-Block "poison surface block" #t #f ())
  (1544 Poison-Surface-Block "poison surface block" #t #f ())
  (1545 Poison-Surface-Block "poison surface block" #t #f ())
  (1546 Poison-Full-Block "poison full block" #t #f ())
  (1547 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1548 Liquid-Lava-Shallow-Block "liquid lava shallow block" #t #f ())
  (1549 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1550 Liquid-Lava-Small-Block "liquid lava small block" #t #f ())
  (1551 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1552 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1553 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1554 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1555 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1556 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1557 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1558 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1559 Bottomless-Swamp-Shallow-Block "bottomless swamp shallow block" #t #f ())
  (1560 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1561 Bottomless-Swamp-Small-Block "bottomless swamp small block" #t #f ())
  (1562 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1563 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1564 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1565 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1566 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1567 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1568 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1569 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1570 Filthy-Water-Shallow-Block "filthy water shallow block" #t #f ())
  (1571 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1572 Filthy-Water-Small-Block "filthy water small block" #t #f ())
  (1573 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1574 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1575 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1576 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1577 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1578 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1579 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1580 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1581 Sea-Water-Shallow-Block "sea water shallow block" #t #f ())
  (1582 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1583 Sea-Water-Small-Block "sea water small block" #t #f ())
  (1584 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1585 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1586 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1587 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1588 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1589 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1590 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1591 Plasma-Full-Block "plasma full block" #t #f ())
  (1592 Plasma-Shallow-Block "plasma shallow block" #t #f ())
  (1593 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1594 Plasma-Small-Block "plasma small block" #t #f ())
  (1595 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1596 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1597 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1598 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1599 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1600 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1601 Plasma-Full-Block "plasma full block" #t #f ())
  (1603 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1604 Clear-Water-Shallow-Block "clear water shallow block" #t #f ())
  (1605 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1606 Clear-Water-Small-Block "clear water small block" #t #f ())
  (1607 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1608 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1609 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1610 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1611 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1612 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1613 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1614 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1615 Hot-Water-Shallow-Block "hot water shallow block" #t #f ())
  (1616 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1617 Hot-Water-Small-Block "hot water small block" #t #f ())
  (1618 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1619 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1620 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1621 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1622 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1623 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1624 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1625 Poison-Full-Block "poison full block" #t #f ())
  (1626 Poison-Shallow-Block "poison shallow block" #t #f ())
  (1627 Poison-Surface-Block "poison surface block" #t #f ())
  (1628 Poison-Small-Block "poison small block" #t #f ())
  (1629 Poison-Surface-Block "poison surface block" #t #f ())
  (1630 Poison-Surface-Block "poison surface block" #t #f ())
  (1631 Poison-Surface-Block "poison surface block" #t #f ())
  (1632 Poison-Surface-Block "poison surface block" #t #f ())
  (1633 Poison-Surface-Block "poison surface block" #t #f ())
  (1634 Poison-Surface-Block "poison surface block" #t #f ())
  (1635 Poison-Full-Block "poison full block" #t #f ())
  (1636 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1637 Liquid-Lava-Shallow-Block "liquid lava shallow block" #t #f ())
  (1638 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1639 Liquid-Lava-Small-Block "liquid lava small block" #t #f ())
  (1640 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1641 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1642 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1643 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1644 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1645 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1646 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1647 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1648 Bottomless-Swamp-Shallow-Block "bottomless swamp shallow block" #t #f ())
  (1649 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1650 Bottomless-Swamp-Small-Block "bottomless swamp small block" #t #f ())
  (1651 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1652 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1653 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1654 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1655 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1656 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1657 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1658 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1659 Filthy-Water-Shallow-Block "filthy water shallow block" #t #f ())
  (1660 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1661 Filthy-Water-Small-Block "filthy water small block" #t #f ())
  (1662 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1663 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1664 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1665 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1666 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1667 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1668 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1669 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1670 Sea-Water-Shallow-Block "sea water shallow block" #t #f ())
  (1671 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1672 Sea-Water-Small-Block "sea water small block" #t #f ())
  (1673 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1674 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1675 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1676 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1677 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1678 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1679 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1680 Plasma-Full-Block "plasma full block" #t #f ())
  (1681 Plasma-Shallow-Block "plasma shallow block" #t #f ())
  (1682 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1683 Plasma-Small-Block "plasma small block" #t #f ())
  (1684 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1685 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1686 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1687 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1688 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1689 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1690 Plasma-Full-Block "plasma full block" #t #f ())
  (1692 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1693 Clear-Water-Shallow-Block "clear water shallow block" #t #f ())
  (1694 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1695 Clear-Water-Small-Block "clear water small block" #t #f ())
  (1696 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1697 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1698 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1699 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1700 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1701 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1702 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1703 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1704 Hot-Water-Shallow-Block "hot water shallow block" #t #f ())
  (1705 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1706 Hot-Water-Small-Block "hot water small block" #t #f ())
  (1707 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1708 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1709 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1710 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1711 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1712 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1713 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1714 Poison-Full-Block "poison full block" #t #f ())
  (1715 Poison-Shallow-Block "poison shallow block" #t #f ())
  (1716 Poison-Surface-Block "poison surface block" #t #f ())
  (1717 Poison-Small-Block "poison small block" #t #f ())
  (1718 Poison-Surface-Block "poison surface block" #t #f ())
  (1719 Poison-Surface-Block "poison surface block" #t #f ())
  (1720 Poison-Surface-Block "poison surface block" #t #f ())
  (1721 Poison-Surface-Block "poison surface block" #t #f ())
  (1722 Poison-Surface-Block "poison surface block" #t #f ())
  (1723 Poison-Surface-Block "poison surface block" #t #f ())
  (1724 Poison-Full-Block "poison full block" #t #f ())
  (1725 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1726 Liquid-Lava-Shallow-Block "liquid lava shallow block" #t #f ())
  (1727 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1728 Liquid-Lava-Small-Block "liquid lava small block" #t #f ())
  (1729 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1730 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1731 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1732 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1733 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1734 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1735 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1736 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1737 Bottomless-Swamp-Shallow-Block "bottomless swamp shallow block" #t #f ())
  (1738 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1739 Bottomless-Swamp-Small-Block "bottomless swamp small block" #t #f ())
  (1740 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1741 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1742 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1743 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1744 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1745 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1746 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1747 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1748 Filthy-Water-Shallow-Block "filthy water shallow block" #t #f ())
  (1749 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1750 Filthy-Water-Small-Block "filthy water small block" #t #f ())
  (1751 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1752 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1753 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1754 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1755 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1756 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1757 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1758 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1759 Sea-Water-Shallow-Block "sea water shallow block" #t #f ())
  (1760 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1761 Sea-Water-Small-Block "sea water small block" #t #f ())
  (1762 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1763 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1764 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1765 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1766 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1767 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1768 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1769 Plasma-Full-Block "plasma full block" #t #f ())
  (1770 Plasma-Shallow-Block "plasma shallow block" #t #f ())
  (1771 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1772 Plasma-Small-Block "plasma small block" #t #f ())
  (1773 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1774 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1775 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1776 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1777 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1778 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1779 Plasma-Full-Block "plasma full block" #t #f ())
  (1781 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1782 Clear-Water-Shallow-Block "clear water shallow block" #t #f ())
  (1783 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1784 Clear-Water-Small-Block "clear water small block" #t #f ())
  (1785 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1786 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1787 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1788 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1789 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1790 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1791 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1792 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1793 Hot-Water-Shallow-Block "hot water shallow block" #t #f ())
  (1794 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1795 Hot-Water-Small-Block "hot water small block" #t #f ())
  (1796 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1797 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1798 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1799 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1800 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1801 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1802 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1803 Poison-Full-Block "poison full block" #t #f ())
  (1804 Poison-Shallow-Block "poison shallow block" #t #f ())
  (1805 Poison-Surface-Block "poison surface block" #t #f ())
  (1806 Poison-Small-Block "poison small block" #t #f ())
  (1807 Poison-Surface-Block "poison surface block" #t #f ())
  (1808 Poison-Surface-Block "poison surface block" #t #f ())
  (1809 Poison-Surface-Block "poison surface block" #t #f ())
  (1810 Poison-Surface-Block "poison surface block" #t #f ())
  (1811 Poison-Surface-Block "poison surface block" #t #f ())
  (1812 Poison-Surface-Block "poison surface block" #t #f ())
  (1813 Poison-Full-Block "poison full block" #t #f ())
  (1814 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1815 Liquid-Lava-Shallow-Block "liquid lava shallow block" #t #f ())
  (1816 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1817 Liquid-Lava-Small-Block "liquid lava small block" #t #f ())
  (1818 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1819 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1820 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1821 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1822 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1823 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1824 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1825 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1826 Bottomless-Swamp-Shallow-Block "bottomless swamp shallow block" #t #f ())
  (1827 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1828 Bottomless-Swamp-Small-Block "bottomless swamp small block" #t #f ())
  (1829 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1830 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1831 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1832 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1833 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1834 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1835 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1836 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1837 Filthy-Water-Shallow-Block "filthy water shallow block" #t #f ())
  (1838 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1839 Filthy-Water-Small-Block "filthy water small block" #t #f ())
  (1840 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1841 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1842 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1843 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1844 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1845 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1846 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1847 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1848 Sea-Water-Shallow-Block "sea water shallow block" #t #f ())
  (1849 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1850 Sea-Water-Small-Block "sea water small block" #t #f ())
  (1851 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1852 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1853 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1854 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1855 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1856 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1857 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1858 Plasma-Full-Block "plasma full block" #t #f ())
  (1859 Plasma-Shallow-Block "plasma shallow block" #t #f ())
  (1860 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1861 Plasma-Small-Block "plasma small block" #t #f ())
  (1862 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1863 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1864 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1865 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1866 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1867 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1868 Plasma-Full-Block "plasma full block" #t #f ())
  (1870 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1871 Clear-Water-Shallow-Block "clear water shallow block" #t #f ())
  (1872 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1873 Clear-Water-Small-Block "clear water small block" #t #f ())
  (1874 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1875 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1876 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1877 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1878 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1879 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1880 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1881 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1882 Hot-Water-Shallow-Block "hot water shallow block" #t #f ())
  (1883 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1884 Hot-Water-Small-Block "hot water small block" #t #f ())
  (1885 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1886 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1887 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1888 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1889 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1890 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1891 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1892 Poison-Full-Block "poison full block" #t #f ())
  (1893 Poison-Shallow-Block "poison shallow block" #t #f ())
  (1894 Poison-Surface-Block "poison surface block" #t #f ())
  (1895 Poison-Small-Block "poison small block" #t #f ())
  (1896 Poison-Surface-Block "poison surface block" #t #f ())
  (1897 Poison-Surface-Block "poison surface block" #t #f ())
  (1898 Poison-Surface-Block "poison surface block" #t #f ())
  (1899 Poison-Surface-Block "poison surface block" #t #f ())
  (1900 Poison-Surface-Block "poison surface block" #t #f ())
  (1901 Poison-Surface-Block "poison surface block" #t #f ())
  (1902 Poison-Full-Block "poison full block" #t #f ())
  (1903 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1904 Liquid-Lava-Shallow-Block "liquid lava shallow block" #t #f ())
  (1905 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1906 Liquid-Lava-Small-Block "liquid lava small block" #t #f ())
  (1907 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1908 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1909 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1910 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1911 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1912 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1913 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1914 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1915 Bottomless-Swamp-Shallow-Block "bottomless swamp shallow block" #t #f ())
  (1916 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1917 Bottomless-Swamp-Small-Block "bottomless swamp small block" #t #f ())
  (1918 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1919 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1920 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1921 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1922 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1923 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (1924 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (1925 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1926 Filthy-Water-Shallow-Block "filthy water shallow block" #t #f ())
  (1927 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1928 Filthy-Water-Small-Block "filthy water small block" #t #f ())
  (1929 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1930 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1931 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1932 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1933 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1934 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (1935 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (1936 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1937 Sea-Water-Shallow-Block "sea water shallow block" #t #f ())
  (1938 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1939 Sea-Water-Small-Block "sea water small block" #t #f ())
  (1940 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1941 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1942 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1943 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1944 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1945 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (1946 Sea-Water-Full-Block "sea water full block" #t #f ())
  (1947 Plasma-Full-Block "plasma full block" #t #f ())
  (1948 Plasma-Shallow-Block "plasma shallow block" #t #f ())
  (1949 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1950 Plasma-Small-Block "plasma small block" #t #f ())
  (1951 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1952 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1953 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1954 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1955 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1956 Plasma-Surface-Block "plasma surface block" #t #f ())
  (1957 Plasma-Full-Block "plasma full block" #t #f ())
  (1959 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1960 Clear-Water-Shallow-Block "clear water shallow block" #t #f ())
  (1961 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1962 Clear-Water-Small-Block "clear water small block" #t #f ())
  (1963 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1964 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1965 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1966 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1967 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1968 Clear-Water-Surface-Block "clear water surface block" #t #f ())
  (1969 Clear-Water-Full-Block "clear water full block" #t #f ())
  (1970 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1971 Hot-Water-Shallow-Block "hot water shallow block" #t #f ())
  (1972 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1973 Hot-Water-Small-Block "hot water small block" #t #f ())
  (1974 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1975 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1976 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1977 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1978 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1979 Hot-Water-Surface-Block "hot water surface block" #t #f ())
  (1980 Hot-Water-Full-Block "hot water full block" #t #f ())
  (1981 Poison-Full-Block "poison full block" #t #f ())
  (1982 Poison-Shallow-Block "poison shallow block" #t #f ())
  (1983 Poison-Surface-Block "poison surface block" #t #f ())
  (1984 Poison-Small-Block "poison small block" #t #f ())
  (1985 Poison-Surface-Block "poison surface block" #t #f ())
  (1986 Poison-Surface-Block "poison surface block" #t #f ())
  (1987 Poison-Surface-Block "poison surface block" #t #f ())
  (1988 Poison-Surface-Block "poison surface block" #t #f ())
  (1989 Poison-Surface-Block "poison surface block" #t #f ())
  (1990 Poison-Surface-Block "poison surface block" #t #f ())
  (1991 Poison-Full-Block "poison full block" #t #f ())
  (1992 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (1993 Liquid-Lava-Shallow-Block "liquid lava shallow block" #t #f ())
  (1994 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1995 Liquid-Lava-Small-Block "liquid lava small block" #t #f ())
  (1996 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1997 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1998 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (1999 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (2000 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (2001 Liquid-Lava-Surface-Block "liquid lava surface block" #t #f ())
  (2002 Liquid-Lava-Full-Block "liquid lava full block" #t #f ())
  (2003 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (2004 Bottomless-Swamp-Shallow-Block "bottomless swamp shallow block" #t #f ())
  (2005 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (2006 Bottomless-Swamp-Small-Block "bottomless swamp small block" #t #f ())
  (2007 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (2008 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (2009 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (2010 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (2011 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (2012 Bottomless-Swamp-Surface-Block "bottomless swamp surface block" #t #f ())
  (2013 Bottomless-Swamp-Full-Block "bottomless swamp full block" #t #f ())
  (2014 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (2015 Filthy-Water-Shallow-Block "filthy water shallow block" #t #f ())
  (2016 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (2017 Filthy-Water-Small-Block "filthy water small block" #t #f ())
  (2018 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (2019 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (2020 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (2021 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (2022 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (2023 Filthy-Water-Surface-Block "filthy water surface block" #t #f ())
  (2024 Filthy-Water-Full-Block "filthy water full block" #t #f ())
  (2025 Sea-Water-Full-Block "sea water full block" #t #f ())
  (2026 Sea-Water-Shallow-Block "sea water shallow block" #t #f ())
  (2027 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (2028 Sea-Water-Small-Block "sea water small block" #t #f ())
  (2029 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (2030 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (2031 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (2032 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (2033 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (2034 Sea-Water-Surface-Block "sea water surface block" #t #f ())
  (2035 Sea-Water-Full-Block "sea water full block" #t #f ())
  (2036 Plasma-Full-Block "plasma full block" #t #f ())
  (2037 Plasma-Shallow-Block "plasma shallow block" #t #f ())
  (2038 Plasma-Surface-Block "plasma surface block" #t #f ())
  (2039 Plasma-Small-Block "plasma small block" #t #f ())
  (2040 Plasma-Surface-Block "plasma surface block" #t #f ())
  (2041 Plasma-Surface-Block "plasma surface block" #t #f ())
  (2042 Plasma-Surface-Block "plasma surface block" #t #f ())
  (2043 Plasma-Surface-Block "plasma surface block" #t #f ())
  (2044 Plasma-Surface-Block "plasma surface block" #t #f ())
  (2045 Plasma-Surface-Block "plasma surface block" #t #f ())
  (2046 Plasma-Full-Block "plasma full block" #t #f ()))