#lang typed/racket

(provide Dye Blockdef symbol->blockdef fixnum->blockdef
         (struct-out blockdef))

; WARNING - This file really gives the macro expander a workout!
; So consider making changes in blockdef.rkt instead whenever possible.

(define-type Dye (U 'white 'black 'purple 'pink 'red 'green 'yellow 'blue))

(struct blockdef ([id : Fixnum]
                  [symbol : Symbol]
                  [liquid? : Boolean]
                  [star? : Boolean]
                  [dyes : (Listof (Pairof Dye Fixnum))])
  #:transparent #:type-name Blockdef)

(define-syntax-rule (parseblock id sym lower-name liquid? star? dyes)
  (blockdef id (quote sym) liquid? star? (quote dyes)))

(define-syntax-rule (define-stuff [symbol->blockdef fixnum->blockdef]
                      (id symbol lower-name liquid? star? dyes)
                      ...)
  (begin
    (define (symbol->blockdef x)
      (case x
        [(symbol) (parseblock id symbol lower-name liquid? star? dyes)]
        ...
        [else #f]))
    (define (fixnum->blockdef x)
      (case x
        [(id) (parseblock id symbol lower-name liquid? star? dyes)]
        ...
        [else #f]))))

; From generate-case-expr.rkt
(define-stuff [symbol->blockdef fixnum->blockdef]
  (1 Bedrock "bedrock" #f #f ())
  (2 Earth "earth" #f #f ())
  (3 Grassy-Earth "grassy earth" #f #f ())
  (4 Limegrassy-Earth "limegrassy earth" #f #f ())
  (5 Tilled-Soil "tilled soil" #f #f ())
  (6 Clay "clay" #f #f ())
  (7 Mossy-Earth "mossy earth" #f #f ())
  (8 Chalk "chalk" #f #f ())
  (9 Chunky-Chalk "chunky chalk" #f #f ())
  (10 Obsidian "obsidian" #f #f ())
  (11 Sand "sand" #f #f ())
  (12 Sandstone "sandstone" #f #f ())
  (13 Sandy-Sandstone "sandy sandstone" #f #f ())
  (14 Bloodstone "bloodstone" #f #f ())
  (15 Ash "ash" #f #f ())
  (16 Witchgrassy-Earth "witchgrassy earth*" #f #t ())
  (17 Poisonous-Peat "poisonous peat" #f #f ())
  (18 Snow-Cover "snow cover" #f #f ())
  (19 Snow "snow" #f #f ())
  (20 Ice "ice" #f #f ())
  (21 Clodstone "clodstone" #f #f ())
  (22 Crumbly-Clodstone "crumbly clodstone" #f #f ())
  (23 Basalt "basalt" #f #f ())
  (24 Translucent-Block "translucent block" #f #f ())
  (25 Lava "lava" #f #f ())
  (26 Vault-Wall "vault wall" #f #f ())
  (27 Viny-Vault-Wall "viny vault wall" #f #f ())
  (28 Cracked-Vault-Wall "cracked vault wall" #f #f ())
  (29 Mud-Brick-Wall "mud-brick wall" #f #f ())
  (30 Timbered-Foundation "timbered foundation" #f #f ((white . 277) (black . 278) (purple . 279) (pink . 280) (red . 281) (green . 282) (yellow . 283) (blue . 284)))
  (31 Timbered-Wall-Midsection "timbered wall midsection" #f #f ((white . 285) (black . 286) (purple . 287) (pink . 288) (red . 289) (green . 290) (yellow . 291) (blue . 292)))
  (32 Timbered-Capital "timbered capital" #f #f ((white . 293) (black . 294) (purple . 295) (pink . 296) (red . 297) (green . 298) (yellow . 299) (blue . 300)))
  (33 Hardwood-Pedestal "hardwood pedestal" #f #f ((white . 359) (black . 360) (purple . 361) (pink . 362) (red . 363) (green . 364) (yellow . 365) (blue . 366)))
  (34 Hardwood-Column-Midsection "hardwood column midsection" #f #f ((white . 351) (black . 352) (purple . 353) (pink . 354) (red . 355) (green . 356) (yellow . 357) (blue . 358)))
  (35 Hardwood-Capital "hardwood capital" #f #f ((white . 367) (black . 368) (purple . 369) (pink . 370) (red . 371) (green . 372) (yellow . 373) (blue . 374)))
  (36 Stone-Foundation "stone foundation" #f #f ())
  (37 Stone-Wall-Midsection "stone wall midsection" #f #f ())
  (39 Castle-Foundation "castle foundation" #f #f ())
  (40 Castle-Wall-Midsection "castle wall midsection" #f #f ())
  (41 Castle-Crenellation "castle crenellation" #f #f ())
  (42 Castle-Battlement "castle battlement" #f #f ())
  (43 Wooden-Wall "wooden wall" #f #f ((white . 301) (black . 302) (purple . 303) (pink . 304) (red . 305) (green . 306) (yellow . 307) (blue . 308)))
  (44 Plumberry-Lumber "plumberry lumber" #f #f ())
  (45 Flagstone "flagstone" #f #f ())
  (46 Straw-Floor "straw floor" #f #f ())
  (47 Wooden-Floor "wooden floor" #f #f ((white . 317) (black . 318) (purple . 319) (pink . 320) (red . 321) (green . 322) (yellow . 323) (blue . 324)))
  (48 Hardwood-Tile "hardwood tile" #f #f ((white . 463) (black . 464) (purple . 465) (pink . 466) (red . 467) (green . 468) (yellow . 469) (blue . 470)))
  (49 Purple-Flagstone "purple flagstone" #f #f ())
  (50 Blue-Flagstone "blue flagstone" #f #f ())
  (51 Carpet-Midsection "carpet midsection" #f #f ((white . 375) (black . 376) (purple . 377) (pink . 378) (red . 379) (green . 380) (yellow . 381) (blue . 382)))
  (52 Fancy-Carpet "fancy carpet" #f #f ((white . 269) (black . 270) (purple . 271) (pink . 272) (green . 273) (yellow . 274) (blue . 275) (red . 276)))
  (53 Castle-Tile "castle tile" #f #f ((white . 654) (black . 655) (purple . 656) (pink . 657) (red . 658) (green . 659) (yellow . 660) (blue . 661)))
  (54 Carved-Castle-Tile "carved castle tile" #f #f ((white . 662) (black . 663) (purple . 664) (pink . 665) (red . 666) (green . 667) (yellow . 668) (blue . 669)))
  (57 Bronze-Temple-Tile "bronze temple tile" #f #f ())
  (58 Blue-Temple-Tile "blue temple tile" #f #f ())
  (61 Golemite "golemite*" #f #t ())
  (62 Coal-Vein "coal vein" #f #f ())
  (63 Copper-Vein "copper vein" #f #f ())
  (64 Iron-Vein "iron vein" #f #f ())
  (65 Silver-Vein "silver vein" #f #f ())
  (66 Gold-Vein "gold vein" #f #f ())
  (67 Zenithium-Vein "zenithium vein" #f #f ())
  (68 Ruby-Vein "ruby vein" #f #f ())
  (69 Mythril-Vein "mythril vein" #f #f ())
  (70 Orichalcum-Vein "orichalcum vein" #f #f ())
  (73 Golemite "golemite" #f #f ())
  (74 Palm-Lumber "palm lumber" #f #f ())
  (75 Cedar-Lumber "cedar lumber" #f #f ())
  (76 Time-Honoured-Turf "time-honoured turf" #f #f ())
  (77 8-Bit-Brick "8-bit brick" #f #f ())
  (78 Olde-Worlde-Wall "olde worlde wall" #f #f ())
  (79 Eyewall "eyewall" #f #f ())
  (80 Dummy-Block "dummy block" #f #f ())
  (81 Witchgrassy-Earth "witchgrassy earth" #f #f ())
  (82 Lemongrassy-Earth "lemongrassy earth" #f #f ())
  (83 Unused-Ore "unused ore" #f #f ())
  (85 Strange-Sand "strange sand" #f #f ())
  (86 Unused-Lava-Block "unused lava block" #f #f ())
  (87 Unused-Ice-Block "unused ice block" #f #f ())
  (88 Bonestone "bonestone" #f #f ())
  (89 Hargon-Block "hargon block" #f #f ())
  (90 Slimy-Block "slimy block" #f #f ())
  (91 Retro-Roof "retro roof" #f #f ())
  (92 Black-Block "black block" #f #f ())
  (93 Grey-Block "grey block" #f #f ())
  (94 White-Block "white block" #f #f ())
  (95 Burgundy-Block "burgundy block" #f #f ())
  (96 Red-Block "red block" #f #f ())
  (97 Purple-Block "purple block" #f #f ())
  (98 Pink-Block "pink block" #f #f ())
  (99 Green-Block "green block" #f #f ())
  (100 Lime-Green-Block "lime-green block" #f #f ())
  (101 Orange-Block "orange block" #f #f ())
  (102 Yellow-Block "yellow block" #f #f ())
  (103 Navy-Block "navy block" #f #f ())
  (104 Blue-Block "blue block" #f #f ())
  (105 Beige-Block "beige block" #f #f ())
  (106 Cyan-Block "cyan block" #f #f ())
  (107 Silver-Block "silver block" #f #f ())
  (108 Gold-Block "gold block" #f #f ())
  (109 Fortress-Foundation "fortress foundation" #f #f ())
  (110 Fortress-Wall-Midsection "fortress wall midsection" #f #f ())
  (111 Fortress-Battlement "fortress battlement" #f #f ())
  (115 Clodstone "clodstone*" #f #t ())
  (118 Crumbly-Clodstone "crumbly clodstone" #f #f ())
  (119 Tilled-Soil "tilled soil" #f #f ())
  (120 Clear-water-full-block "clear water full block" #t #f ())
  (121 Clear-water-surface-block "clear water surface block" #t #f ())
  (122 Clear-water-surface-block "clear water surface block" #t #f ())
  (123 Clear-water-surface-block "clear water surface block" #t #f ())
  (124 Witchgrassy-Block "witchgrassy block*" #f #t ())
  (125 Lemongrassy-Block "lemongrassy block*" #f #t ())
  (126 Grassy-Block "grassy block*" #f #t ())
  (127 Limegrassy-Block "limegrassy block*" #f #t ())
  (128 Clear-water-full-block "clear water full block" #t #f ())
  (130 Light-Dolomite "light dolomite" #f #f ())
  (131 Dark-Dolomite "dark dolomite" #f #f ())
  (132 Stony-Sand "stony sand" #f #f ())
  (134 Masonry-Wall "masonry wall" #f #f ())
  (138 Mossy-Bark "mossy bark" #f #f ())
  (139 Bark "bark" #f #f ())
  (141 Stony-Soil "stony soil" #f #f ())
  (142 Clear-water-surface-block "clear water surface block" #t #f ())
  (143 Clear-water-surface-block "clear water surface block" #t #f ())
  (144 Clear-water-surface-block "clear water surface block" #t #f ())
  (145 Clear-water-shallow-block "clear water shallow block" #t #f ())
  (146 Seaside-Sand "seaside sand" #f #f ())
  (147 Arid-Earth "arid earth" #f #f ())
  (149 Chert "chert" #f #f ())
  (153 Chunky-Chert "chunky chert" #f #f ())
  (155 Leaves "leaves" #f #f ())
  (156 Spoiled-Soil "spoiled soil" #f #f ())
  (158 Moss "moss" #f #f ())
  (161 Humus "humus" #f #f ())
  (162 Tilled-Humus "tilled humus" #f #f ())
  (163 Obsidian "obsidian*" #f #t ())
  (164 Blue-Temple-Tile "blue temple tile*" #f #t ())
  (165 Chert "chert*" #f #t ())
  (166 Citadel-Battlement "citadel battlement*" #f #t ())
  (167 Golden-Citadel-Capital "golden citadel capital*" #f #t ())
  (168 Alcoved-Citadel-Wall "alcoved citadel wall*" #f #t ())
  (169 Golden-Citadel-Foundation "golden citadel foundation*" #f #t ())
  (170 Sanguine-Cinders "sanguine cinders*" #f #t ())
  (171 Scales "scales*" #f #t ())
  (172 Tilled-Soil "tilled soil" #f #f ())
  (173 Tilled-Humus "tilled humus" #f #f ())
  (174 Chert "chert" #f #f ())
  (175 Bubbling-Seaside-Sand "bubbling seaside sand" #f #f ())
  (176 Patterned-Citadel-Wall "patterned citadel wall*" #f #t ())
  (177 Citadel-Capital "citadel capital*" #f #t ())
  (178 Citadel-Foundation "citadel foundation*" #f #t ())
  (179 Castle-Wall-Midsection "castle wall midsection*" #f #t ())
  (180 Citadel-Floor "citadel floor*" #f #t ())
  (182 Poison-shallow-block "poison shallow block" #t #f ())
  (183 Poison-surface-block "poison surface block" #t #f ())
  (184 Poison-surface-block "poison surface block" #t #f ())
  (185 Poison-surface-block "poison surface block" #t #f ())
  (186 Poison-surface-block "poison surface block" #t #f ())
  (187 Poison-surface-block "poison surface block" #t #f ())
  (188 Poison-surface-block "poison surface block" #t #f ())
  (189 Poison-full-block "poison full block" #t #f ())
  (190 Poison-full-block "poison full block" #t #f ())
  (191 Bottomless-Swamp-shallow-block "bottomless swamp shallow block" #t #f ())
  (192 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (193 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (194 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (195 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (196 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (197 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (198 Bottomless-Swamp-full-block "bottomless swamp full block" #t #f ())
  (199 Bottomless-Swamp-full-block "bottomless swamp full block" #t #f ())
  (200 Muddy-Water-shallow-block "muddy water shallow block" #t #f ())
  (201 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (202 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (203 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (204 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (205 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (206 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (207 Muddy-Water-full-block "muddy water full block" #t #f ())
  (208 Muddy-Water-full-block "muddy water full block" #t #f ())
  (209 Umber "umber" #f #f ())
  (210 Umber-Sandstone-Block "umber sandstone block*" #f #t ())
  (223 Hot-Water-shallow-block "hot water shallow block" #t #f ())
  (224 Hot-Water-surface-block "hot water surface block" #t #f ())
  (225 Hot-Water-surface-block "hot water surface block" #t #f ())
  (226 Hot-Water-surface-block "hot water surface block" #t #f ())
  (227 Hot-Water-surface-block "hot water surface block" #t #f ())
  (228 Hot-Water-surface-block "hot water surface block" #t #f ())
  (229 Hot-Water-surface-block "hot water surface block" #t #f ())
  (230 Hot-Water-full-block "hot water full block" #t #f ())
  (231 Hot-Water-full-block "hot water full block" #t #f ())
  (232 Mossy-Spoiled-Soil "mossy spoiled soil" #f #f ())
  (234 Swampy-Soil "swampy soil" #f #f ())
  (235 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (236 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (239 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (241 Lumpy-Umber "lumpy umber" #f #f ())
  (243 Softwood "softwood" #f #f ())
  (244 Floorboard "floorboard" #f #f ((white . 570) (black . 571) (purple . 572) (pink . 573) (red . 574) (green . 575) (yellow . 576) (blue . 577)))
  (247 Yellow-frame-block "yellow frame block*" #f #t ())
  (256 Moss "moss" #f #f ())
  (259 Lava-shallow-block "lava shallow block" #t #f ())
  (260 Lava-surface-block "lava surface block" #t #f ())
  (261 Lava-surface-block "lava surface block" #t #f ())
  (262 Lava-surface-block "lava surface block" #t #f ())
  (263 Lava-surface-block "lava surface block" #t #f ())
  (263 Chalk "chalk" #f #f ())
  (264 Lava-surface-block "lava surface block" #t #f ())
  (265 Lava-surface-block "lava surface block" #t #f ())
  (266 Lava-surface-block "lava surface block" #t #f ())
  (267 Lava-surface-block "lava surface block" #t #f ())
  (268 Patterned-Vault-Wall "patterned vault wall" #f #f ())
  (331 Shifting-Sand "shifting sand" #f #f ())
  (333 Sea-water-shallow-block "sea water shallow block" #t #f ())
  (334 Sea-water-surface-block "sea water surface block" #t #f ())
  (335 Sea-water-surface-block "sea water surface block" #t #f ())
  (336 Sea-water-surface-block "sea water surface block" #t #f ())
  (337 Sea-water-surface-block "sea water surface block" #t #f ())
  (338 Sea-water-surface-block "sea water surface block" #t #f ())
  (339 Sea-water-surface-block "sea water surface block" #t #f ())
  (340 Sea-water-full-block "sea water full block" #t #f ())
  (341 Sea-water-full-block "sea water full block" #t #f ())
  (343 Clear-water-shallow-block "clear water shallow block" #t #f ())
  (344 Hot-water-shallow-block "hot water shallow block" #t #f ())
  (345 Poison-shallow-block "poison shallow block" #t #f ())
  (346 Lava-shallow-block "lava shallow block" #t #f ())
  (347 Bottomless-Swamp-shallow-block "bottomless swamp shallow block" #t #f ())
  (348 Muddy-Water-shallow-block "muddy water shallow block" #t #f ())
  (349 Sea-water-shallow-block "sea water shallow block" #t #f ())
  (383 Clear-water-surface-block "clear water surface block" #t #f ())
  (384 Hot-water-surface-block "hot water surface block" #t #f ())
  (385 Poison-surface-block "poison surface block" #t #f ())
  (386 Lava-surface-block "lava surface block" #t #f ())
  (387 Bottomless-Swamp-surface-block "bottomless swamp surface block" #t #f ())
  (388 Muddy-Water-surface-block "muddy water surface block" #t #f ())
  (389 Sea-water-surface-block "sea water surface block" #t #f ())
  (390 Plasma-shallow-block "plasma shallow block" #t #f ())
  (391 Plasma-surface-block "plasma surface block" #t #f ())
  (392 Plasma-surface-block "plasma surface block" #t #f ())
  (393 Plasma-surface-block "plasma surface block" #t #f ())
  (394 Plasma-surface-block "plasma surface block" #t #f ())
  (395 Plasma-surface-block "plasma surface block" #t #f ())
  (396 Plasma-surface-block "plasma surface block" #t #f ())
  (397 Plasma-full-block "plasma full block" #t #f ())
  (398 Plasma-full-block "plasma full block" #t #f ())
  (399 Plasma-shallow-block "plasma shallow block" #t #f ())
  (400 Plasma-surface-block "plasma surface block" #t #f ())
  (401 Vault-Tile "vault tile" #f #f ())
  (402 Gold-Brick "gold brick" #f #f ())
  (403 Spaceship-Wall "spaceship wall" #f #f ((white . 421) (black . 422) (purple . 423) (pink . 424) (red . 425) (green . 426) (yellow . 427) (blue . 428)))
  (404 Shiny-Spaceship-Wall "shiny spaceship wall" #f #f ((white . 429) (black . 430) (purple . 431) (pink . 432) (red . 433) (green . 434) (yellow . 435) (blue . 436)))
  (405 Citadel-Battlement "citadel battlement" #f #f ())
  (407 Golden-Citadel-Capital "golden citadel capital" #f #f ())
  (408 Alcoved-Citadel-Wall "alcoved citadel wall" #f #f ())
  (409 Golden-Citadel-Foundation "golden citadel foundation" #f #f ())
  (410 Patterned-Citadel-Wall "patterned citadel wall" #f #f ())
  (411 Golden-Tile "golden tile" #f #f ())
  (412 Hargon-Block "hargon block*" #f #t ())
  (413 Black-Void "black void" #f #f ())
  (414 Earth "earth*" #f #t ())
  (415 Mossy-Earth "mossy earth*" #f #t ())
  (416 Snow "snow*" #f #t ())
  (417 Clodstone "clodstone*" #f #t ())
  (418 Witchgrassy-Earth "witchgrassy earth*" #f #t ())
  (419 Battlefield-Earth "battlefield earth" #f #f ())
  (420 Sea-water-shallow-block "sea water shallow block" #t #f ())
  (437 Woodless-Timbered-Wall "woodless timbered wall" #f #f ())
  (438 Banded-Timbered-Wall "banded timbered wall" #f #f ((white . 447) (black . 448) (purple . 449) (pink . 450) (red . 451) (green . 452) (yellow . 453) (blue . 454)))
  (472 Red-Brick-Wall "red-brick wall" #f #f ())
  (473 Diamond-Vein "diamond vein" #f #f ())
  (474 Chert-Red "chert (red)*" #f #t ())
  (475 Citadel-Floor-Red "citadel floor (red)*" #f #t ())
  (476 Magnetite-Vein "magnetite vein" #f #f ())
  (477 Siltstone "siltstone" #f #f ())
  (481 Slimy-Block "slimy block" #f #f ())
  (484 Red-Brick-Floor "red-brick floor" #f #f ())
  (485 Crazing-Paving "crazing paving" #f #f ())
  (486 Copper-Wall "copper wall" #f #f ())
  (487 Marble "marble" #f #f ())
  (488 Silver-Birch-Lumber "silver birch lumber" #f #f ())
  (489 Spoiled-Soil "spoiled soil*" #f #t ())
  (491 Dark-Bark "dark bark" #f #f ())
  (492 Teal-Leaves "teal leaves" #f #f ())
  (497 Bloodstained-Soil "bloodstained soil" #f #f ())
  (498 Bloodstained-Soil-full "bloodstained soil full" #f #f ())
  (499 Padded-Floor "padded floor" #f #f ((white . 578) (black . 579) (purple . 580) (pink . 581) (red . 582) (green . 583) (yellow . 584) (blue . 585)))
  (500 Leafy-Spoiled-Soil "leafy spoiled soil" #f #f ())
  (501 Leafy-Spoiled-Soil-full "leafy spoiled soil full" #f #f ())
  (519 Cracked-Floorboard "cracked floorboard" #f #f ())
  (520 Blackened-Bark "blackened bark" #f #f ())
  (521 Bloodstained-Soil-full "bloodstained soil full" #f #f ())
  (522 Malachite "malachite" #f #f ())
  (523 Patterned-Vault-Wall "patterned vault wall*" #f #t ())
  (524 Patterned-Vault-Wall "patterned vault wall*" #f #t ())
  (525 Adobe-Capital "adobe capital" #f #f ())
  (526 Adobe-Wall-Midsection "adobe wall (midsection)" #f #f ())
  (527 Adobe-Pedestal "adobe pedestal" #f #f ())
  (528 Alcoved-Adobe-Wall "alcoved adobe wall" #f #f ())
  (529 Copper-Floor "copper floor" #f #f ())
  (530 Sooty-Softwood "sooty softwood" #f #f ())
  (532 Heartwood "heartwood" #f #f ())
  (533 Plumberry-Lumber "plumberry lumber*" #f #t ())
  (534 White-Dye-Vein "white dye vein" #f #f ())
  (535 Black-Dye-Vein "black dye vein" #f #f ())
  (536 Purple-Dye-Vein "purple dye vein" #f #f ())
  (537 Pink-Dye-Vein "pink dye vein" #f #f ())
  (538 Red-Dye-Vein "red dye vein" #f #f ())
  (539 Green-Dye-Vein "green dye vein" #f #f ())
  (540 Yellow-Dye-Vein "yellow dye vein" #f #f ())
  (541 Blue-Dye-Vein "blue dye vein" #f #f ())
  (543 Blue-Temple-Tile-Half-Dummy "blue temple tile half dummy" #f #f ())
  (544 Carpet "carpet" #f #f ((white . 309) (black . 310) (purple . 311) (pink . 312) (red . 313) (green . 314) (yellow . 315) (blue . 316)))
  (545 Golden-Castle-Capital "golden castle capital" #f #f ())
  (546 Alcoved-Castle-Wall "alcoved castle wall" #f #f ())
  (547 Golden-Castle-Foundation "golden castle foundation" #f #f ())
  (548 Cracked-Castle-Tile "cracked castle tile" #f #f ())
  (549 Battlefield-Earth "battlefield earth" #f #f ())
  (550 Citadel-Capital "citadel capital" #f #f ())
  (551 Citadel-Foundation "citadel foundation" #f #f ())
  (552 Citadel-Wall-Midsection "citadel wall midsection" #f #f ())
  (553 Citadel-Floor "citadel floor" #f #f ())
  (560 Ghost-Block "ghost block*" #f #t ())
  (561 Plaster "plaster" #f #f ((white . 562) (black . 563) (purple . 564) (pink . 565) (red . 566) (green . 567) (yellow . 568) (blue . 569)))
  (586 Leafy-Stony-Soil "leafy stony soil" #f #f ())
  (587 Leafy-Stony-Soil-Full "leafy stony soil full" #f #f ())
  (588 Iron-Block "iron block" #f #f ((white . 638) (black . 639) (purple . 640) (pink . 641) (red . 642) (green . 643) (yellow . 644) (blue . 645)))
  (589 Concrete-Block "concrete block" #f #f ())
  (590 Sun-Sigil-Block "sun sigil block" #f #f ())
  (591 Star-Sigil-Block "star sigil block" #f #f ())
  (592 Moon-Sigil-Block "moon sigil block" #f #f ())
  (593 Water-Sigil-Block "water sigil block" #f #f ())
  (594 Soul-Sigil-Block "soul sigil block" #f #f ())
  (595 Sandstone-Brick "sandstone brick" #f #f ((white . 646) (black . 647) (purple . 648) (pink . 649) (red . 650) (green . 651) (yellow . 652) (blue . 653)))
  (596 Withered-Leaves "withered leaves" #f #f ())
  (598 Arid-Earth "arid earth*" #f #t ())
  (599 Umber "umber*" #f #t ())
  (600 Mossy-Spoiled-Soil "mossy spoiled soil*" #f #t ())
  (601 Swampy-Soil "swampy soil*" #f #t ())
  (602 Lumpy-Umber "lumpy umber*" #f #t ())
  (603 Bloodstained-Soil "bloodstained soil*" #f #t ())
  (604 Leafy-Spoiled-Soil "leafy spoiled soil" #f #f ())
  (606 Sanguine-Sandstone "sanguine sandstone" #f #f ())
  (607 Sanguine-Cinders "sanguine cinders" #f #f ())
  (608 Sanguine-Sand "sanguine sand" #f #f ())
  (609 Sanguine-Sandy-Sandstone "sanguine sandy sandstone" #f #f ())
  (610 Scales "scales" #f #f ())
  (611 Red-Block "red block*" #f #t ())
  (612 Silver-Brick "silver brick" #f #f ())
  (613 Sooty-Silver-Brick "sooty silver brick" #f #f ())
  (614 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (615 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (616 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (617 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (618 Seeded-Spoiled-Soil "seeded spoiled soil" #f #f ())
  (619 Obsidian "obsidian*" #f #t ())
  (620 Sand "sand*" #f #t ())
  (621 Lava "lava*" #f #t ())
  (622 Umber-Sandstone-Block "umber sandstone block*" #f #t ())
  (624 Silver-Tile "silver tile" #f #f ())
  (625 Obsidian "obsidian" #f #f ())
  (626 Light-Dolomite "light dolomite" #f #f ())
  (627 Clodstone "clodstone" #f #f ())
  (630 Masonry-Wall "masonry wall" #f #f ())
  (631 Patterned-Vault-Wall "patterned vault wall" #f #f ())
  (632 Patterned-Vault-Wall "patterned vault wall" #f #f ())
  (633 Vault-Tile "vault tile" #f #f ())
  (634 Vault-Wall "vault wall" #f #f ())
  (635 Viny-Vault-Wall "viny vault wall" #f #f ())
  (636 Cracked-Vault-Wall "cracked vault wall" #f #f ())
  (637 Black-Void "black void" #f #f ())
  (670 Cyan-Block "cyan block*" #f #t ())
  (671 Green-Block "green block*" #f #t ())
  (672 Purple-Block "purple block*" #f #t ())
  (673 Translucent-Block "translucent block" #f #f ())
  (674 Yellow-Block "yellow block*" #f #t ())
  (675 Orange-Block "orange block*" #f #t ())
  (676 Blue-Block "blue block*" #f #t ())
  (677 Cyan-Block "cyan block*" #f #t ())
  (678 Bronze-Temple-Tile "bronze temple tile" #f #f ())
  (679 Blue-Temple-Tile "blue temple tile" #f #f ())
  (680 Seeded-Limegrassy-Earth "seeded limegrassy earth" #f #f ())
  (681 Seeded-Mossy-Spoiled-Soil "seeded mossy spoiled soil" #f #f ())
  (682 Seeded-Sand "seeded sand" #f #f ())
  (683 Seeded-Earth "seeded earth" #f #f ())
  (684 Seeded-Snow "seeded snow" #f #f ())
  (685 Seeded-Grassy-Earth "seeded grassy earth" #f #f ())
  (686 Gravel-Block "gravel block" #f #f ())
  (687 Scaled-Wall-Block "scaled wall block" #f #f ((white . 694) (black . 695) (purple . 696) (pink . 697) (red . 698) (green . 699) (yellow . 700) (blue . 701)))
  (688 Slatted-Wall-Block "slatted wall block" #f #f ())
  (689 Woven-Straw-Block "woven straw block" #f #f ())
  (690 Woven-Straw-Block "woven straw block" #f #f ())
  (691 Woven-Straw-Block "woven straw block" #f #f ())
  (692 Woven-Straw-Block "woven straw block" #f #f ())
  (693 Woven-Straw-Block "woven straw block" #f #f ())
  (702 Polka-Dot-Block "polka-dot block" #f #f ((white . 703) (black . 704) (purple . 705) (pink . 706) (red . 707) (green . 708) (yellow . 709) (blue . 710)))
  (711 Faux-Floral-Floor-Block "faux floral floor block" #f #f ())
  (712 Palm-Patterned-Block "palm-patterned block" #f #f ((white . 732) (black . 733) (purple . 734) (pink . 735) (red . 736) (green . 737) (yellow . 738) (blue . 739)))
  (713 Fruity-Fiend-Block "fruity fiend block" #f #f ())
  (714 Chequered-Block "chequered block" #f #f ((white . 740) (black . 741) (purple . 742) (pink . 743) (red . 744) (green . 745) (yellow . 746) (blue . 747)))
  (715 Sunset-Styled-Block "sunset-styled block" #f #f ((white . 834) (black . 835) (purple . 836) (pink . 837) (red . 838) (green . 839) (yellow . 840) (blue . 841)))
  (716 Seaweed-Styled-Block "seaweed-styled block" #f #f ((white . 842) (black . 843) (purple . 844) (pink . 845) (red . 846) (green . 847) (yellow . 848) (blue . 849)))
  (717 Stylish-Stripy-Block "stylish stripy block" #f #f ((white . 748) (black . 749) (purple . 750) (pink . 751) (red . 752) (green . 753) (yellow . 754) (blue . 755)))
  (718 Seaside-Scene-Block "seaside scene block" #f #f ())
  (719 Abstract-Floral-Floor-Block "abstract floral floor block" #f #f ())
  (720 Herringbone-Floorboard-Block "herringbone floorboard block" #f #f ((white . 756) (black . 757) (purple . 758) (pink . 759) (red . 760) (green . 761) (yellow . 762) (blue . 763)))
  (721 Night-Sky-Wall-Block "night sky wall block" #f #f ((white . 764) (black . 765) (purple . 766) (pink . 767) (red . 768) (green . 769) (yellow . 770) (blue . 771)))
  (722 Granite-Floor-Block "granite floor block" #f #f ())
  (723 Stucco-Wall-Block "stucco wall block" #f #f ((white . 724) (black . 725) (purple . 726) (pink . 727) (red . 728) (green . 729) (yellow . 730) (blue . 731)))
  (772 Modern-Masonry-Block "modern masonry block" #f #f ((white . 773) (black . 774) (purple . 775) (pink . 776) (red . 777) (green . 778) (yellow . 779) (blue . 780)))
  (781 Chintzy-Block "chintzy block" #f #f ((white . 782) (black . 783) (purple . 784) (pink . 785) (red . 786) (green . 787) (yellow . 788) (blue . 789)))
  (790 Gingham-Carpet "gingham carpet" #f #f ((white . 791) (black . 792) (purple . 793) (pink . 794) (red . 795) (green . 796) (yellow . 797) (blue . 798)))
  (799 Stripy-Wall "stripy wall" #f #f ((white . 800) (black . 801) (purple . 802) (pink . 803) (red . 804) (green . 805) (yellow . 806) (blue . 807)))
  (808 Mottled-Wall "mottled wall" #f #f ((white . 809) (black . 810) (purple . 811) (pink . 812) (red . 813) (green . 814) (yellow . 815) (blue . 816)))
  (817 Slimy-Wall "slimy wall" #f #f ())
  (818 Diamond-Design-Block "diamond design block" #f #f ())
  (819 Old-Skool-Wall-Block "old-skool wall block" #f #f ())
  (820 Art-Deco-Block "art deco block" #f #f ())
  (821 Jungle-Wall "jungle wall" #f #f ())
  (822 Vintage-Wall "vintage wall" #f #f ((white . 850) (black . 851) (purple . 852) (pink . 853) (red . 854) (green . 855) (yellow . 856) (blue . 857)))
  (823 Damask-Design-Block "damask design block" #f #f ((white . 824) (black . 825) (purple . 826) (pink . 827) (red . 828) (green . 829) (yellow . 830) (blue . 831)))
  (832 Refined-Design-Block "refined design block" #f #f ())
  (833 Classy-Cross-Block "classy cross block" #f #f ())
  (1012 Black-Void "black void" #f #f ())
  )
