#lang typed/racket

(provide IoA
         Furrowfield
         Khrumbul-Dun
         Moonbrooke
         Malhalla
         Anglers-Isle
         Skelkatraz
         parse-map
         )

(require "basics.rkt")

(module+ test
  (require typed/rackunit))

(define (parse-map [rows : (Listof (Listof (U '_ 'X)))])
  (let ([chunk-id -1])
    (for/vector : (Vectorof (Vectorof (U #f Integer)))
      ([row rows])
      (for/vector : (Vectorof (U #f Integer))
        ([cell row])
        (case cell
          [(_) #f]
          [(X) (begin (set! chunk-id (+ 1 chunk-id))
                      chunk-id)]
          [else (error "assert fail")])))))

(define IoA : Chunk-Layout
  (parse-map '((_ _ _ _ _ _ _ X X X X X X X X _ _ _ X X X _ _ _ _ _ _)
               (_ _ _ _ _ _ X X X X X X X X X X X X X X X X X _ _ _ _)
               (_ _ _ _ X X X X X X X X X X X X X X X X X X X _ _ _ _)
               (_ _ _ X X X X X X X X X X X X X X X X X X X X _ _ _ _)
               (_ _ X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (_ X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ X X X X X X X X X X X X X X X X X X X X X X X _ _ _)
               (_ _ X X X X X X X X X X X X X X X X X X X X X _ _ _ _)
               (_ _ X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _)
               (_ _ _ _ X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ X X X X X X _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _))))

(module+ test
  (check-equal? (chunk-count IoA) 369))

(define Furrowfield : Chunk-Layout
  (parse-map '((_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X _ _ _ X X X _ _ X X X X _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X _ X X X _ _ _ X X X X _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X _ _ _ _ X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X _ _ X X X _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X _ _ _ _ X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X _ _ _ X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X _ _ _ X X X X _ _ X X _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X _ _ _ X X X X X _ _ X _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X _ _ _ X X X X _ _ X X _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ X X _ _ _ _ _ X X X X X)
               (_ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ X X X X X X _ _ X X X X X)
               (_ X X X _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X X X X _ X X _ _ X X X X X)
               (X X X X X _ _ X X _ _ X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ X X X X X)
               (X X X X X _ X X X _ _ X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ X X X X X)
               (X X X X X _ X X X X X X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _ _)
               (X X X X _ _ _ X X _ X X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X _ X X X X X X X X X X X X X X X _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X _ _ _ _ _ _ _ _ X X X X X _ _ _ _ X X X _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X _ _ _ _ _ _ _))))

(module+ test
  (check-equal? (chunk-count Furrowfield) 591))

(define Khrumbul-Dun : Chunk-Layout
  (parse-map '((_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X _ X X X X X _ _ _)
               (X X X X _ X X X X X X X X X X X X X X X X X X X X X X _ _ _)
               (_ X X X _ X X X X X X X X X X X X X X X X X X X X X _ _ _ _)
               (_ X X X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _)
               (_ X X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _)
               (X X X X X X X X X X X X X X X X X X X X X X X X X X X _ _ _)
               (_ X X X X X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ X X X X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ _ X X X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ X X X X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ X X X X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ _ X X X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X _ _)
               (_ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X _ _)
               (_ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X _ _)
               (_ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X)
               (_ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (_ _ _ X X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (_ _ X X X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (_ _ X X X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (_ _ X X X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (_ _ X X X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (_ _ X X X X X X X X X X _ _ _ X X X X X X X X X X X X X X X)
               (_ X X _ X X X X X X _ _ X X _ X X X X X X X X X X X X X X X)
               (_ _ _ _ _ _ _ X X _ _ _ _ _ X X X X X X X X X _ X X X X X X)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X _ X X X X X _))))

(module+ test
  (check-equal? (chunk-count Khrumbul-Dun) 637))

(define Moonbrooke : Chunk-Layout
  (parse-map '((_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X _ _ X X X X X X X X _ _ _)
               (_ X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X _ _ _)
               (X X X X X X X X X _ _ _ _ X X X _ _ _ _ _ X X X X X X X X X X X X X X _)
               (X X X X X X X X X X X X X X X X X _ _ _ X X X X X X X X X X X X X X X _)
               (_ X X X X X X X X X X X X X X X X X X X _ X X X X X X X X X X X X X X _)
               (_ X X X X _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ X X _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X X X X _)
               (_ _ _ _ _ _ _ _ _ _ _ X X X X X X X _ _ _ _ X X X X X X X X X X X X X _)
               (_ _ _ _ _ _ _ _ _ _ _ X X X X X _ _ _ _ _ X X X X X X X X X X X X X _ _)
               (_ _ _ _ _ _ _ _ _ _ _ X X X X _ _ _ _ _ _ X X X X X X X X X X X X X _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X X)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X X _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _))))

(module+ test
  (check-equal? (chunk-count Moonbrooke) 700))

(define Malhalla : Chunk-Layout
  (parse-map '((_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X _ _ _ _ _ _ _ _)
               (_ _ _ X X X X X _ X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _)
               (_ _ X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _)
               (X X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _)
               (X X X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _)
               (X X X X X X X X X X X X X X X X X X X X X X _ _ _ X X X X _ _ _ _)
               (X X X X X X X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _)
               (X X X X X X X X X X X X X X X X X X X X X X X X X X X X X _ _ _ _)
               (X X X X X X X X X X X X X X X X X X X X _ X X X _ X X X X _ _ _ _)
               (X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ X _ _ _ _ _ _)
               (X X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ X _ _ _ _ _)
               (X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (X X X X X X X X X X X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (X X X X X X X X X X X X X _ _ _ _ _ X _ _ _ _ X X _ _ X _ _ _ _ _)
               (_ X X X X X X X X X X X _ _ _ _ _ _ _ X X X X X X X X _ _ _ _ _ _)
               (_ X X X X X X X X X X X _ _ _ _ _ _ _ X X X X X X X X _ _ _ _ _ _)
               (_ _ X X X X X X X X X X _ _ _ _ _ _ _ X X X X X X X X _ _ _ _ _ _)
               (_ _ X X X X X X X X _ _ _ _ _ _ _ _ _ X X X X X X X X _ _ _ _ _ _)
               (_ _ X X X X X X X X X X _ _ _ _ _ _ _ X X X X X X X X _ _ _ _ _ _)
               (_ _ X X X X X X X X X X _ _ _ _ _ _ _ X X X X X X X X _ _ _ _ _ _)
               (_ X X X X X X X X X X X X _ _ _ _ _ _ X X X X X X X X _ _ _ _ _ _)
               (_ X X X X X X X X X X X X _ _ _ _ _ _ X X X X X X X X _ _ _ _ _ _)
               (_ X X X X X X X X X X X X X _ _ _ _ X _ _ _ _ _ _ _ _ X _ _ _ X _)
               (_ X X X X X X X X X X X X X X X _ _ _ _ X X X X X _ _ _ _ _ X X X)
               (_ X X X X X X X X X X X X X X X X X X X X X X X X X _ X X X X X X)
               (_ _ _ X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X)
               (_ _ _ _ _ _ X _ _ _ _ _ _ _ X X X X X X X X X X X X X X X X X X X)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X X X X X _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X X X X X X X _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X X _ X X X _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X _ _ _ _ _ _ _ _ _ _ _ _ _))))

(module+ test
  (check-equal? (chunk-count Malhalla) 691))

(define Anglers-Isle : Chunk-Layout
  (parse-map '((_ _ X X X X X X _ _ _)
               (_ X X X X X X X X X X)
               (_ X X X X X X X X X X)
               (_ X X X X X X X X X _)
               (_ X X X X X X X X X _)
               (_ X X X X X X X X X _)
               (X X X X X X X X X X _)
               (X X X X X X X X X X X)
               (X X X X X X X X X X _)
               (_ _ _ X X X _ _ X X _))))

(module+ test
  (check-equal? (chunk-count Anglers-Isle) 89))

(define Skelkatraz : Chunk-Layout
  (parse-map '((_ _ _ _ _ _ _ _ X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ X X X X)
               (_ X X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ X X X X)
               (_ X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ X X X X)
               (_ X X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ X X X X)
               (X X X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (X X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ X X X X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
               (_ _ _ X X X X X X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _))))

(module+ test
  (check-equal? (chunk-count Skelkatraz) 155))

(define small-soggy-skerry : Chunk-Layout
  (parse-map '((X X X X X X X)
               (X X X X X X X)
               (X X X X X X X)
               (X X X X X X X)
               (X X X X X X X)
               (X X X X X X X)
               (X X X X X X X)
               (_ X X _ _ _ _)
               (_ X X _ _ _ _))))

(define small-coral-cay : Chunk-Layout
  (parse-map '((X X X _ X X X)
               (X X X X X X X)
               (X X X X X X X)
               (X X X X X X X)
               (X X X X X X X)
               (X X X X X X X)
               (X X X X X _ _)
               (_ X X _ _ _ _)
               (_ X X _ _ _ _))))

(define med-soggy-skerry : Chunk-Layout
  (parse-map '((X X X X X X X X X X)
               (X X X X X X X X X X)
               (X X X X X X X X X X)
               (X X X X X X X X X X)
               (X X X X X X X X X X)
               (X X X X X X X X X X)
               (X X X X X X X X X X)
               (X X X X X X X X X X)
               (X X X X X X X X X X)
               (X X X X X X X X X X)
               (_ X X _ _ _ _ _ _ _)
               (_ X X _ _ _ _ _ _ _))))

(define med-coral-cay : Chunk-Layout
  (parse-map '((X X X X X X X X _ _)
               (X X X X X X X X X X)
               (X X X X X X X X X X)
               (X X X X X X X X X X)
               (X X X X X X X X X _)
               (X X X X X X X X X _)
               (X X X X X X X X X _)
               (X X X X X X X X X _)
               (X X X X X X X X X _)
               (_ _ _ X X X _ _ _ _)
               (_ X X _ _ _ _ _ _ _)
               (_ X X _ _ _ _ _ _ _))))

(define large-soggy-skerry : Chunk-Layout
  (parse-map '((X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X _)
               (X X X X X X X X X X X X _)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (_ X X _ _ _ _ _ _ _ _ _ _)
               (_ X X _ _ _ _ _ _ _ _ _ _))))

(define large-soggy-skerry2 : Chunk-Layout
  (parse-map '((X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (X X X X X X X X X X X X X)
               (_ _ _ X X X X X X X X X X)
               (_ X X _ _ _ _ _ _ _ _ _ _)
               (_ X X _ _ _ _ _ _ _ _ _ _))))

(define large-coral-cay : Chunk-Layout
  (parse-map '((X X X X X X X X X X X)
               (X X X X X X X X X X X)
               (X X X X X X X X X X X)
               (X X X X X X X X X X X)
               (X X X X X X X X X X X)
               (X X X X X X X X X X X)
               (X X X X X X X X X X X)
               (X X X X X X X X X X X)
               (X X X X X X X X X X X)
               (X X X X X X X X X X X)
               (X X X X X X X X X X X)
               (_ _ _ _ _ _ _ _ _ _ _)
               (X X _ _ _ _ _ _ _ _ _)
               (X X _ _ _ _ _ _ _ _ _))))
